openapi: 3.1.0
info:
  title: "ProHelper Admin API"
  description: |
    Базовая спецификация Admin API. Добавляйте пути через `$ref` в папку `paths/`.
  version: "1.0.0"
servers:
  - url: "/api/v1/admin"
    description: "Production server"
  - url: "http://localhost:8000/api/v1/admin"
    description: "Local development"
paths:
  $ref: './paths/index.yaml'

components:
  securitySchemes:
    $ref: './components/securitySchemes.yaml'
  schemas:
    ApiResponse:
      $ref: './components/schemas/ApiResponse.yaml'
    ErrorResponse:
      $ref: './components/schemas/ErrorResponse.yaml'
    LoginRequest:
      $ref: './components/schemas/LoginRequest.yaml'
    LoginResponse:
      $ref: './components/schemas/LoginResponse.yaml'
    UserSimple:
      $ref: './components/schemas/UserSimple.yaml'
    ContractorSummaryReport:
      $ref: './components/schemas/ContractorSummaryReport.yaml'
    ContractorDetailReport:
      $ref: './components/schemas/ContractorDetailReport.yaml'
  parameters: {}
  responses:
    UnauthorizedError:
      $ref: './components/responses/UnauthorizedError.yaml'