lint:
  extends:
    - recommended
  rules:
    operation-parameters: off

apis:
  adminApi:
    root: docs/openapi/admin/openapi.yaml
  lkApi:
    root: docs/openapi/lk/openapi.yaml
  mobileApi:
    root: docs/openapi/mobile/openapi.yaml 