features:
  openapi:
    lint:
      extends:
        - recommended
      rules:
        operation-parameters: off

apis:
  adminApi: docs/openapi/admin/openapi.yaml
  lkApi: docs/openapi/lk/openapi.yaml
  mobileApi: docs/openapi/mobile/openapi.yaml 