rules:
  rule/operation-parameters: off

apis:
  admin@v1:
    root: docs/openapi/admin/openapi.yaml
  lk@v1:
    root: docs/openapi/lk/openapi.yaml
  mobile@v1:
    root: docs/openapi/mobile/openapi.yaml 