openapi: 3.0.0
info:
  title: Contractors API
  version: v1
tags:
  - name: Contractors
    description: Операции с подрядчиками (контрагентами)
paths:
  /api/v1/admin/contractors:
    get:
      tags: [Contractors]
      summary: Получить список подрядчиков
      description: Получает пагинированный список всех подрядчиков организации.
      security:
        - bearerAuth: []
      parameters:
        - name: per_page
          in: query
          description: Количество элементов на странице
          required: false
          schema:
            type: integer
            default: 15
        - name: page
          in: query
          description: Номер страницы
          required: false
          schema:
            type: integer
            default: 1
        - name: name
          in: query
          description: Фильтр по наименованию подрядчика (частичное совпадение)
          required: false
          schema:
            type: string
        - name: inn
          in: query
          description: Фильтр по ИНН (точное совпадение)
          required: false
          schema:
            type: string
        - name: sort_by
          in: query
          description: Поле для сортировки
          required: false
          schema:
            type: string
            default: name
            enum: [id, name, inn, created_at, updated_at]
        - name: sort_direction
          in: query
          description: Направление сортировки
          required: false
          schema:
            type: string
            enum: [asc, desc]
            default: asc
      responses:
        '200':
          description: Список подрядчиков
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Contractor'
                  links:
                    $ref: 'common_components.yaml#/components/schemas/PaginationLinks'
                  meta:
                    $ref: 'common_components.yaml#/components/schemas/PaginationMeta'
        '400': { $ref: 'common_components.yaml#/components/responses/BadRequest' }
        '401': { $ref: 'common_components.yaml#/components/responses/Unauthorized' }
        '403': { $ref: 'common_components.yaml#/components/responses/Forbidden' }
        '500': { $ref: 'common_components.yaml#/components/responses/InternalError' }
    post:
      tags: [Contractors]
      summary: Создать нового подрядчика
      description: Создает нового подрядчика в системе.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoreContractorRequest'
      responses:
        '201':
          description: Подрядчик успешно создан
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Contractor'
        '400': { $ref: 'common_components.yaml#/components/responses/BadRequest' }
        '401': { $ref: 'common_components.yaml#/components/responses/Unauthorized' }
        '403': { $ref: 'common_components.yaml#/components/responses/Forbidden' }
        '422': { $ref: 'common_components.yaml#/components/responses/ValidationError' }
        '500': { $ref: 'common_components.yaml#/components/responses/InternalError' }

  /api/v1/admin/contractors/{contractor}:
    get:
      tags: [Contractors]
      summary: Получить информацию о подрядчике
      description: Получает детальную информацию о подрядчике по его ID.
      security:
        - bearerAuth: []
      parameters:
        - name: contractor
          in: path
          required: true
          description: ID подрядчика
          schema:
            type: integer
      responses:
        '200':
          description: Информация о подрядчике
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Contractor'
        '401': { $ref: 'common_components.yaml#/components/responses/Unauthorized' }
        '403': { $ref: 'common_components.yaml#/components/responses/Forbidden' }
        '404': { $ref: 'common_components.yaml#/components/responses/NotFound' }
        '500': { $ref: 'common_components.yaml#/components/responses/InternalError' }
    put:
      tags: [Contractors]
      summary: Обновить информацию о подрядчике
      description: Обновляет данные указанного подрядчика.
      security:
        - bearerAuth: []
      parameters:
        - name: contractor
          in: path
          required: true
          description: ID подрядчика
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateContractorRequest'
      responses:
        '200':
          description: Подрядчик успешно обновлен
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Contractor'
        '400': { $ref: 'common_components.yaml#/components/responses/BadRequest' }
        '401': { $ref: 'common_components.yaml#/components/responses/Unauthorized' }
        '403': { $ref: 'common_components.yaml#/components/responses/Forbidden' }
        '404': { $ref: 'common_components.yaml#/components/responses/NotFound' }
        '422': { $ref: 'common_components.yaml#/components/responses/ValidationError' }
        '500': { $ref: 'common_components.yaml#/components/responses/InternalError' }
    delete:
      tags: [Contractors]
      summary: Удалить подрядчика
      description: Удаляет указанного подрядчика из системы. (Soft delete)
      security:
        - bearerAuth: []
      parameters:
        - name: contractor
          in: path
          required: true
          description: ID подрядчика
          schema:
            type: integer
      responses:
        '204':
          description: Подрядчик успешно удален (No Content)
        '400': { $ref: 'common_components.yaml#/components/responses/BadRequest' }
        '401': { $ref: 'common_components.yaml#/components/responses/Unauthorized' }
        '403': { $ref: 'common_components.yaml#/components/responses/Forbidden' }
        '404': { $ref: 'common_components.yaml#/components/responses/NotFound' }
        '500': { $ref: 'common_components.yaml#/components/responses/InternalError' }

components:
  schemas:
    StoreContractorRequest:
      type: object
      description: Данные для создания нового подрядчика
      required:
        - name
      properties:
        name:
          type: string
          maxLength: 255
          description: Полное наименование подрядчика
        contact_person:
          type: string
          maxLength: 255
          nullable: true
          description: Контактное лицо
        phone:
          type: string
          maxLength: 50
          nullable: true
          description: Контактный телефон
        email:
          type: string
          format: email
          maxLength: 255
          nullable: true
          description: Электронная почта
        legal_address:
          type: string
          maxLength: 1000
          nullable: true
          description: Юридический адрес
        inn:
          type: string
          maxLength: 12
          nullable: true
          description: "ИНН (Индивидуальный налоговый номер)"
        kpp:
          type: string
          maxLength: 9
          nullable: true
          description: "КПП (Код причины постановки на учет), только для юр.лиц"
        bank_details:
          type: string
          nullable: true
          description: Банковские реквизиты
        notes:
          type: string
          nullable: true
          description: Дополнительные примечания

    UpdateContractorRequest:
      type: object
      description: Данные для обновления подрядчика
      properties:
        name:
          type: string
          maxLength: 255
          description: "Полное наименование подрядчика. Обязательно, если передается."
        contact_person:
          type: string
          maxLength: 255
          nullable: true
          description: Контактное лицо
        phone:
          type: string
          maxLength: 50
          nullable: true
          description: Контактный телефон
        email:
          type: string
          format: email
          maxLength: 255
          nullable: true
          description: Электронная почта
        legal_address:
          type: string
          maxLength: 1000
          nullable: true
          description: Юридический адрес
        inn:
          type: string
          maxLength: 12
          nullable: true
          description: ИНН
        kpp:
          type: string
          maxLength: 9
          nullable: true
          description: КПП
        bank_details:
          type: string
          nullable: true
          description: Банковские реквизиты
        notes:
          type: string
          nullable: true
          description: Дополнительные примечания

    Contractor:
      type: object
      description: Полная информация о подрядчике
      properties:
        id:
          type: integer
          format: int64
          description: Уникальный идентификатор подрядчика
          readOnly: true
        organization_id:
          type: integer
          format: int64
          description: Идентификатор организации, к которой относится подрядчик
          readOnly: true # Обычно устанавливается автоматически
        name:
          type: string
          maxLength: 255
          description: Полное наименование подрядчика
        contact_person:
          type: string
          maxLength: 255
          nullable: true
          description: Контактное лицо
        phone:
          type: string
          maxLength: 50
          nullable: true
          description: Контактный телефон
        email:
          type: string
          format: email
          maxLength: 255
          nullable: true
          description: Электронная почта
        legal_address:
          type: string
          maxLength: 1000
          nullable: true
          description: Юридический адрес
        inn:
          type: string
          maxLength: 12
          nullable: true
          description: "ИНН (Индивидуальный налоговый номер)"
        kpp:
          type: string
          maxLength: 9
          nullable: true
          description: "КПП (Код причины постановки на учет), только для юр.лиц"
        bank_details:
          type: string
          nullable: true
          description: Банковские реквизиты
        notes:
          type: string
          nullable: true
          description: Дополнительные примечания
        created_at:
          type: string
          format: date-time
          description: Дата и время создания записи
          readOnly: true
        updated_at:
          type: string
          format: date-time
          description: Дата и время последнего обновления записи
          readOnly: true
        deleted_at:
          type: string
          format: date-time
          nullable: true
          description: Дата и время мягкого удаления записи (если применимо)
          readOnly: true
      required:
        - id
        - organization_id
        - name
        - created_at
        - updated_at

  securitySchemes:
    bearerAuth: { $ref: 'common_components.yaml#/components/securitySchemes/bearerAuth' } 