<?php

declare(strict_types=1);

namespace Tests\Feature\AssetManagement;

use App\BusinessModules\Core\AssetManagement\Enums\AssetLifecycleStatus;
use App\BusinessModules\Core\AssetManagement\Models\OrganizationAsset;
use App\BusinessModules\Core\AssetManagement\Services\LegacyAssetMapper;
use App\Models\Organization;
use Illuminate\Contracts\Console\Kernel;
use Illuminate\Database\PostgresConnection;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\TestCase;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\Attributes\Test;
use ReflectionClass;
use stdClass;

#[Group('postgres-contract')]
final class LegacyAssetMapperPostgresContractTest extends TestCase
{
    use DatabaseTransactions;

    private int $organizationId;

    public function createApplication()
    {
        $app = require dirname(__DIR__, 3).'/bootstrap/app.php';
        $app->make(Kernel::class)->bootstrap();

        return $app;
    }

    protected function setUp(): void
    {
        parent::setUp();
        self::assertSame('1', getenv('RUN_ESTIMATE_GENERATION_POSTGRES_CONTRACT'));
        self::assertInstanceOf(PostgresConnection::class, DB::connection());
        self::assertSame('public', (string) DB::scalar('SELECT current_schema()'));

        foreach ([
            'measurement_units' => 'database/migrations/2025_01_01_000015_create_measurement_units_table.php',
            'materials' => 'database/migrations/2025_01_01_000035_create_materials_table.php',
            'organization_warehouses' => 'app/BusinessModules/Features/BasicWarehouse/migrations/2025_10_13_000002_create_organization_warehouses_table.php',
        ] as $table => $migration) {
            if (! Schema::hasTable($table)) {
                (require dirname(__DIR__, 3).'/'.$migration)->up();
            }
        }
        if (! Schema::hasTable('machinery')) {
            DB::statement('CREATE TABLE machinery (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)');
        }
        if (! Schema::hasTable('organization_assets')) {
            (require dirname(__DIR__, 3).'/database/migrations/2026_08_10_000001_create_organization_assets_table.php')->up();
        }

        $organization = Organization::withoutEvents(fn (): Organization => Organization::query()->create([
            'name' => 'Организация контракта техники',
            'is_active' => true,
        ]));
        $this->organizationId = (int) $organization->id;
    }

    #[Test]
    public function exact_active_canonical_link_is_accepted(): void
    {
        $asset = $this->createAsset();

        self::assertSame($asset->id, $this->matchingLinkedMachineryAsset($this->legacy($asset))->id);
    }

    #[Test]
    #[DataProvider('invalidCanonicalLinks')]
    public function explicit_link_fails_closed_for_noncanonical_identity(string $mutation): void
    {
        $asset = $this->createAsset();
        $legacy = $this->legacy($asset);

        match ($mutation) {
            'retired' => $asset->update(['lifecycle_status' => AssetLifecycleStatus::Retired->value]),
            'deleted' => $asset->delete(),
            'cross_tenant' => $legacy->organization_id++,
            'name' => $legacy->name = 'Другой экскаватор',
            'inventory' => $legacy->inventory_number = 'OTHER-INVENTORY',
            'ownership' => $legacy->ownership_type = 'rented',
            'machinery' => $legacy->machinery_id = 999999,
            'asset_type' => $asset->update(['metadata' => [
                'asset_type' => 'warehouse_item',
                'canonical_source' => 'machinery_operations',
            ]]),
            'canonical_source' => $asset->update(['metadata' => [
                'asset_type' => 'machinery',
                'canonical_source' => 'warehouse_balances',
            ]]),
        };

        self::assertNull($this->matchingLinkedMachineryAsset($legacy));
    }

    /** @return array<string, array{string}> */
    public static function invalidCanonicalLinks(): array
    {
        return [
            'retired asset' => ['retired'],
            'soft deleted asset' => ['deleted'],
            'cross tenant link' => ['cross_tenant'],
            'different name' => ['name'],
            'different inventory identity' => ['inventory'],
            'different ownership' => ['ownership'],
            'different machinery identity' => ['machinery'],
            'foreign asset type' => ['asset_type'],
            'foreign canonical source' => ['canonical_source'],
        ];
    }

    private function createAsset(): OrganizationAsset
    {
        return OrganizationAsset::query()->create([
            'organization_id' => $this->organizationId,
            'machinery_id' => null,
            'name' => 'Экскаватор',
            'inventory_number' => 'INV-'.$this->organizationId,
            'ownership_type' => 'owned',
            'lifecycle_status' => AssetLifecycleStatus::Active->value,
            'technical_status' => 'serviceable',
            'metadata' => [
                'asset_type' => 'machinery',
                'canonical_source' => 'machinery_operations',
            ],
        ]);
    }

    private function legacy(OrganizationAsset $asset): stdClass
    {
        return (object) [
            'organization_asset_id' => $asset->id,
            'organization_id' => $this->organizationId,
            'name' => $asset->name,
            'inventory_number' => $asset->inventory_number,
            'asset_code' => null,
            'ownership_type' => $asset->ownership_type,
            'machinery_id' => null,
        ];
    }

    private function matchingLinkedMachineryAsset(stdClass $legacy): ?OrganizationAsset
    {
        $mapper = (new ReflectionClass(LegacyAssetMapper::class))->newInstanceWithoutConstructor();
        $method = (new ReflectionClass(LegacyAssetMapper::class))->getMethod('matchingLinkedMachineryAsset');

        return $method->invoke($mapper, $legacy);
    }
}
