<?php

declare(strict_types=1);

namespace Tests\Feature\AssetManagement;

use App\BusinessModules\Core\AssetManagement\Enums\AssetLifecycleStatus;
use App\BusinessModules\Core\AssetManagement\Services\LegacyAssetMapper;
use Illuminate\Contracts\Console\Kernel;
use Illuminate\Database\PostgresConnection;
use Illuminate\Foundation\Testing\TestCase;
use Illuminate\Support\Facades\DB;
use PHPUnit\Framework\Attributes\Test;
use ReflectionClass;
use stdClass;

final class LegacyAssetMapperPostgresContractTest extends TestCase
{
    private PostgresConnection $connection;

    private string $schema;

    public function createApplication()
    {
        $app = require dirname(__DIR__, 3).'/bootstrap/app.php';
        $app->make(Kernel::class)->bootstrap();

        return $app;
    }

    protected function setUp(): void
    {
        parent::setUp();
        self::assertSame('1', getenv('RUN_ESTIMATE_GENERATION_POSTGRES_CONTRACT'));
        $connection = DB::connection();
        self::assertInstanceOf(PostgresConnection::class, $connection);
        $this->connection = $connection;
        $this->schema = 'most_ci_legacy_asset_mapper_'.bin2hex(random_bytes(8));
        $this->connection->unprepared('CREATE SCHEMA "'.$this->schema.'"');
        $this->connection->unprepared('SET search_path TO "'.$this->schema.'"');
        $this->connection->unprepared(<<<'SQL'
            CREATE TABLE organization_assets (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                organization_id bigint NOT NULL,
                name varchar(255) NOT NULL,
                inventory_number varchar(255) NOT NULL,
                ownership_type varchar(64) NOT NULL,
                machinery_id bigint NULL,
                lifecycle_status varchar(64) NOT NULL,
                metadata jsonb NOT NULL,
                deleted_at timestamp NULL,
                created_at timestamp NULL,
                updated_at timestamp NULL
            )
            SQL);
    }

    protected function tearDown(): void
    {
        $this->connection->unprepared('SET search_path TO public');
        $this->connection->unprepared('DROP SCHEMA "'.$this->schema.'" CASCADE');
        parent::tearDown();
    }

    #[Test]
    public function explicit_link_requires_active_canonical_machinery_identity(): void
    {
        $legacy = (object) [
            'organization_asset_id' => 91,
            'organization_id' => 38,
            'name' => 'Экскаватор',
            'inventory_number' => 'INV-91',
            'asset_code' => 'ASSET-91',
            'ownership_type' => 'owned',
            'machinery_id' => 17,
        ];

        foreach ([
            [AssetLifecycleStatus::Retired->value, ['asset_type' => 'machinery', 'canonical_source' => 'machinery_operations']],
            [AssetLifecycleStatus::Active->value, ['asset_type' => 'warehouse_item', 'canonical_source' => 'machinery_operations']],
            [AssetLifecycleStatus::Active->value, ['asset_type' => 'machinery', 'canonical_source' => 'warehouse_balances']],
        ] as [$lifecycleStatus, $metadata]) {
            $this->connection->table('organization_assets')->delete();
            $this->connection->table('organization_assets')->insert([
                'id' => 91,
                'organization_id' => 38,
                'name' => 'Экскаватор',
                'inventory_number' => 'INV-91',
                'ownership_type' => 'owned',
                'machinery_id' => 17,
                'lifecycle_status' => $lifecycleStatus,
                'metadata' => json_encode($metadata, JSON_THROW_ON_ERROR),
            ]);

            self::assertNull($this->matchingLinkedMachineryAsset($legacy));
        }
    }

    private function matchingLinkedMachineryAsset(stdClass $legacy): mixed
    {
        $mapper = (new ReflectionClass(LegacyAssetMapper::class))->newInstanceWithoutConstructor();
        $method = (new ReflectionClass(LegacyAssetMapper::class))->getMethod('matchingLinkedMachineryAsset');

        return $method->invoke($mapper, $legacy);
    }
}
