<?php

declare(strict_types=1);

namespace App\BusinessModules\Core\Reporting\Application\Errors;

enum ReportErrorCode: string
{
    case REPORT_NOT_FOUND = 'REPORT_NOT_FOUND';
    case REPORT_SCOPE_FORBIDDEN = 'REPORT_SCOPE_FORBIDDEN';
    case REPORT_REQUEST_INVALID = 'REPORT_REQUEST_INVALID';
    case REPORT_FILTER_UNSUPPORTED = 'REPORT_FILTER_UNSUPPORTED';
    case REPORT_FILTER_VALUE_NOT_FOUND = 'REPORT_FILTER_VALUE_NOT_FOUND';
    case REPORT_FILTER_RANGE_INVALID = 'REPORT_FILTER_RANGE_INVALID';
    case REPORT_SORT_UNSUPPORTED = 'REPORT_SORT_UNSUPPORTED';
    case REPORT_CURSOR_INVALID = 'REPORT_CURSOR_INVALID';
    case REPORT_IDEMPOTENCY_KEY_INVALID = 'REPORT_IDEMPOTENCY_KEY_INVALID';
    case REPORT_IDEMPOTENCY_CONFLICT = 'REPORT_IDEMPOTENCY_CONFLICT';
    case REPORT_SNAPSHOT_NOT_READY = 'REPORT_SNAPSHOT_NOT_READY';
    case REPORT_EXPORT_NOT_READY = 'REPORT_EXPORT_NOT_READY';
    case REPORT_OFFICIAL_SNAPSHOT_UNSEALED = 'REPORT_OFFICIAL_SNAPSHOT_UNSEALED';
    case REPORT_SNAPSHOT_EXPIRED = 'REPORT_SNAPSHOT_EXPIRED';
    case REPORT_EXPORT_EXPIRED = 'REPORT_EXPORT_EXPIRED';
    case REPORT_EXPORT_LIMIT_EXCEEDED = 'REPORT_EXPORT_LIMIT_EXCEEDED';
    case REPORT_RATE_LIMITED = 'REPORT_RATE_LIMITED';
    case REPORT_SOURCE_UNAVAILABLE = 'REPORT_SOURCE_UNAVAILABLE';
    case REPORT_DEPENDENCY_FAILED = 'REPORT_DEPENDENCY_FAILED';
    case REPORT_INTERNAL_ERROR = 'REPORT_INTERNAL_ERROR';
}
