<?php

declare(strict_types=1);

namespace App\BusinessModules\Features\AIAssistant\Services\DomainMetadata;

use App\BusinessModules\Features\AIAssistant\Services\AssistantDomainDefinition;
use App\BusinessModules\Features\AIAssistant\Services\AssistantDataAccessPolicy;
use App\BusinessModules\Features\AIAssistant\Services\Rag\Sources\SalesBusinessRagSource;
use App\Domain\Authorization\Services\AuthorizationService;
use App\Models\User;
use Illuminate\Database\Eloquent\Builder;

final class AssistantSalesBusinessMetadata
{
    public static function recordDefinitions(): array
    {
        return [
            'supplier' => ['model' => \App\Models\Supplier::class, 'domain' => 'sales_supplier_catalog', 'source' => 'sales_supplier_catalog', 'module' => 'catalog-management', 'permissions' => ['suppliers.view'], 'fields' => ['id', 'organization_id', 'name', 'code', 'is_active', 'created_at', 'updated_at'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'marketplace_contractor_category' => ['model' => \App\BusinessModules\ContractorMarketplace\Domain\Models\MarketplaceContractorCategory::class, 'domain' => 'contractor_marketplace', 'source' => 'contractor_marketplace', 'module' => 'contractor-portal', 'permissions' => ['contractor_marketplace.profile.view'], 'fields' => ['id', 'profile_id', 'category_id', 'is_primary', 'experience_years', 'team_capacity', 'min_project_budget', 'max_project_budget', 'rating_score', 'ratings_count', 'completed_projects_count', 'last_completed_at', 'updated_at', 'created_at'], 'parents' => ['profile_id' => ['type' => 'marketplace_contractor_profile', 'nullable' => false], 'category_id' => ['type' => 'marketplace_work_category', 'nullable' => false]], 'organization_column' => null, 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => ['min_project_budget', 'max_project_budget', 'rating_score']],
            'marketplace_contractor_document' => ['model' => \App\BusinessModules\ContractorMarketplace\Domain\Models\MarketplaceContractorDocument::class, 'domain' => 'contractor_marketplace', 'source' => 'contractor_marketplace', 'module' => 'contractor-portal', 'permissions' => ['contractor_marketplace.profile.view'], 'fields' => ['id', 'profile_id', 'type', 'title', 'status', 'verified_at', 'verified_by_user_id', 'updated_at', 'created_at'], 'parents' => ['profile_id' => ['type' => 'marketplace_contractor_profile', 'nullable' => false]], 'organization_column' => null, 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'marketplace_contractor_portfolio_item' => ['model' => \App\BusinessModules\ContractorMarketplace\Domain\Models\MarketplaceContractorPortfolioItem::class, 'domain' => 'contractor_marketplace', 'source' => 'contractor_marketplace', 'module' => 'contractor-portal', 'permissions' => ['contractor_marketplace.profile.view'], 'fields' => ['id', 'profile_id', 'category_id', 'title', 'description', 'city', 'completed_at', 'updated_at', 'created_at'], 'parents' => ['profile_id' => ['type' => 'marketplace_contractor_profile', 'nullable' => false], 'category_id' => ['type' => 'marketplace_work_category', 'nullable' => true]], 'organization_column' => null, 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'marketplace_contractor_profile' => ['model' => \App\BusinessModules\ContractorMarketplace\Domain\Models\MarketplaceContractorProfile::class, 'domain' => 'contractor_marketplace', 'source' => 'contractor_marketplace', 'module' => 'contractor-portal', 'permissions' => ['contractor_marketplace.profile.view'], 'fields' => ['id', 'organization_id', 'status', 'display_name', 'short_description', 'description', 'team_size_min', 'team_size_max', 'years_on_market', 'base_city', 'service_radius_km', 'availability_status', 'available_from', 'verification_level', 'is_visible_in_marketplace', 'published_at', 'updated_at', 'created_at'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'marketplace_contractor_rating' => ['model' => \App\BusinessModules\ContractorMarketplace\Domain\Models\MarketplaceContractorRating::class, 'domain' => 'contractor_marketplace', 'source' => 'contractor_marketplace', 'module' => 'contractor-portal', 'permissions' => ['contractor_marketplace.profile.view'], 'fields' => ['id', 'profile_id', 'category_id', 'score', 'quality_score', 'deadline_score', 'communication_score', 'safety_score', 'financial_discipline_score', 'reviews_count', 'completed_offers_count', 'repeat_hires_count', 'last_recalculated_at', 'updated_at', 'created_at'], 'parents' => ['profile_id' => ['type' => 'marketplace_contractor_profile', 'nullable' => false], 'category_id' => ['type' => 'marketplace_work_category', 'nullable' => false]], 'organization_column' => null, 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => ['score', 'quality_score', 'deadline_score', 'communication_score', 'safety_score', 'financial_discipline_score']],
            'marketplace_contractor_region' => ['model' => \App\BusinessModules\ContractorMarketplace\Domain\Models\MarketplaceContractorRegion::class, 'domain' => 'contractor_marketplace', 'source' => 'contractor_marketplace', 'module' => 'contractor-portal', 'permissions' => ['contractor_marketplace.profile.view'], 'fields' => ['id', 'profile_id', 'country', 'region', 'city', 'is_primary', 'updated_at', 'created_at'], 'parents' => ['profile_id' => ['type' => 'marketplace_contractor_profile', 'nullable' => false]], 'organization_column' => null, 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'marketplace_hiring_offer' => ['model' => \App\BusinessModules\ContractorMarketplace\Domain\Models\MarketplaceHiringOffer::class, 'domain' => 'contractor_marketplace', 'source' => 'contractor_marketplace', 'module' => 'contractor-portal', 'permissions' => ['contractor_marketplace.offers.view'], 'fields' => ['id', 'project_id', 'hiring_organization_id', 'contractor_organization_id', 'contractor_profile_id', 'created_by_user_id', 'responded_by_user_id', 'status', 'role', 'title', 'message', 'starts_at', 'ends_at', 'budget_min', 'budget_max', 'currency', 'expires_at', 'sent_at', 'viewed_at', 'accepted_at', 'declined_at', 'cancelled_at', 'decline_reason', 'status_reason', 'updated_at', 'created_at'], 'parents' => ['contractor_profile_id' => ['type' => 'marketplace_contractor_profile', 'nullable' => false]], 'organization_column' => 'hiring_organization_id', 'project_column' => 'project_id', 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => ['budget_min', 'budget_max']],
            'marketplace_hiring_offer_review' => ['model' => \App\BusinessModules\ContractorMarketplace\Domain\Models\MarketplaceHiringOfferReview::class, 'domain' => 'contractor_marketplace', 'source' => 'contractor_marketplace', 'module' => 'contractor-portal', 'permissions' => ['contractor_marketplace.offers.view'], 'fields' => ['id', 'offer_id', 'project_id', 'reviewer_organization_id', 'contractor_organization_id', 'contractor_profile_id', 'category_id', 'created_by_user_id', 'quality_score', 'deadline_score', 'communication_score', 'safety_score', 'financial_discipline_score', 'comment', 'updated_at', 'created_at'], 'parents' => ['offer_id' => ['type' => 'marketplace_hiring_offer', 'nullable' => false, 'matches' => ['project_id' => 'project_id', 'contractor_organization_id' => 'contractor_organization_id', 'contractor_profile_id' => 'contractor_profile_id']], 'contractor_profile_id' => ['type' => 'marketplace_contractor_profile', 'nullable' => false], 'category_id' => ['type' => 'marketplace_work_category', 'nullable' => false]], 'organization_column' => 'reviewer_organization_id', 'project_column' => 'project_id', 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => ['quality_score', 'deadline_score', 'communication_score', 'safety_score', 'financial_discipline_score']],
            'marketplace_hiring_offer_work_package' => ['model' => \App\BusinessModules\ContractorMarketplace\Domain\Models\MarketplaceHiringOfferWorkPackage::class, 'domain' => 'contractor_marketplace', 'source' => 'contractor_marketplace', 'module' => 'contractor-portal', 'permissions' => ['contractor_marketplace.offers.view'], 'fields' => ['id', 'offer_id', 'category_id', 'title', 'description', 'quantity', 'unit', 'budget_min', 'budget_max', 'starts_at', 'ends_at', 'updated_at', 'created_at'], 'parents' => ['offer_id' => ['type' => 'marketplace_hiring_offer', 'nullable' => false], 'category_id' => ['type' => 'marketplace_work_category', 'nullable' => false]], 'organization_column' => null, 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => ['quantity', 'budget_min', 'budget_max']],
            'marketplace_work_category' => ['model' => \App\BusinessModules\ContractorMarketplace\Domain\Models\MarketplaceWorkCategory::class, 'domain' => 'contractor_marketplace', 'source' => 'contractor_marketplace', 'module' => 'contractor-portal', 'permissions' => ['contractor_marketplace.categories.view'], 'fields' => ['id', 'parent_id', 'slug', 'name', 'type', 'is_active', 'sort_order', 'updated_at', 'created_at'], 'parents' => ['parent_id' => ['type' => 'marketplace_work_category', 'nullable' => true, 'reference_only' => true]], 'organization_column' => null, 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'contractor_scorecard_policy_version' => ['model' => \App\BusinessModules\ContractorMarketplace\Reporting\Scorecard\Models\ContractorScorecardPolicyVersion::class, 'domain' => 'contractor_marketplace', 'source' => 'contractor_marketplace', 'module' => 'contractor-portal', 'permissions' => ['contractor_marketplace.profile.view'], 'fields' => ['id', 'organization_id', 'version', 'minimum_coverage', 'minimum_sample_size', 'effective_from', 'effective_to', 'created_at', 'updated_at'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => ['minimum_coverage']],
            'contractor_scorecard_row' => ['model' => \App\BusinessModules\ContractorMarketplace\Reporting\Scorecard\Models\ContractorScorecardRow::class, 'domain' => 'contractor_marketplace', 'source' => 'contractor_marketplace', 'module' => 'contractor-portal', 'permissions' => ['contractor_marketplace.profile.view'], 'fields' => ['id', 'organization_id', 'snapshot_id', 'profile_id', 'category_id', 'project_id', 'cohort_key', 'component_code', 'unit_code', 'component_mean', 'sample_size', 'eligible_count', 'coverage', 'row_key'], 'parents' => ['profile_id' => ['type' => 'marketplace_contractor_profile', 'nullable' => false], 'category_id' => ['type' => 'marketplace_work_category', 'nullable' => false], 'snapshot_id' => ['type' => 'contractor_scorecard_snapshot', 'nullable' => false]], 'organization_column' => 'organization_id', 'project_column' => 'project_id', 'version_columns' => [], 'numeric_fields' => ['component_mean', 'coverage']],
            'contractor_scorecard_snapshot' => ['model' => \App\BusinessModules\ContractorMarketplace\Reporting\Scorecard\Models\ContractorScorecardSnapshot::class, 'domain' => 'contractor_marketplace', 'source' => 'contractor_marketplace', 'module' => 'contractor-portal', 'permissions' => ['contractor_marketplace.profile.view'], 'fields' => ['id', 'organization_id', 'policy_version_id', 'formula_version', 'as_of', 'generated_at', 'stale_at', 'row_count'], 'parents' => ['policy_version_id' => ['type' => 'contractor_scorecard_policy_version', 'nullable' => false]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['generated_at'], 'numeric_fields' => []],
            'presale_estimate' => ['model' => \App\BusinessModules\Features\PresaleEstimates\Models\PresaleEstimate::class, 'domain' => 'presale_estimates', 'source' => 'presale_estimates', 'module' => null, 'permissions' => ['presale_estimates.view'], 'fields' => ['id', 'organization_id', 'current_version_id', 'accepted_version_id', 'crm_deal_id', 'tender_id', 'commercial_proposal_id', 'project_id', 'contract_id', 'number', 'title', 'status', 'subtotal_amount', 'discount_amount', 'vat_amount', 'total_amount', 'currency', 'created_by_user_id', 'updated_by_user_id', 'updated_at', 'created_at'], 'parents' => ['crm_deal_id' => ['type' => 'crm_deal', 'nullable' => true], 'tender_id' => ['type' => 'tender', 'nullable' => true], 'commercial_proposal_id' => ['type' => 'commercial_proposal', 'nullable' => true], 'contract_id' => ['type' => 'contract', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => 'project_id', 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => ['subtotal_amount', 'discount_amount', 'vat_amount', 'total_amount']],
            'presale_estimate_budget_transfer_operation' => ['model' => \App\BusinessModules\Features\PresaleEstimates\Models\PresaleEstimateBudgetTransferOperation::class, 'domain' => 'presale_estimates', 'source' => 'presale_estimates', 'module' => null, 'permissions' => ['presale_estimates.view'], 'fields' => ['id', 'organization_id', 'source_type', 'source_id', 'presale_estimate_id', 'presale_estimate_version_id', 'project_id', 'contract_id', 'budget_version_id', 'status', 'error_code', 'created_by_user_id', 'completed_at', 'updated_at', 'created_at'], 'parents' => ['presale_estimate_id' => ['type' => 'presale_estimate', 'nullable' => true], 'presale_estimate_version_id' => ['type' => 'presale_estimate_version', 'nullable' => true, 'matches' => ['presale_estimate_id' => 'presale_estimate_id']], 'contract_id' => ['type' => 'contract', 'nullable' => true], 'budget_version_id' => ['type' => 'budget_version', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => 'project_id', 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'presale_estimate_line_item' => ['model' => \App\BusinessModules\Features\PresaleEstimates\Models\PresaleEstimateLineItem::class, 'domain' => 'presale_estimates', 'source' => 'presale_estimates', 'module' => null, 'permissions' => ['presale_estimates.view'], 'fields' => ['id', 'organization_id', 'presale_estimate_id', 'presale_estimate_version_id', 'presale_estimate_section_id', 'budget_article_id', 'responsibility_center_id', 'planned_month', 'line_type', 'title', 'description', 'unit', 'quantity', 'unit_cost', 'discount_amount', 'vat_rate', 'subtotal_amount', 'total_amount', 'sort_order', 'updated_at', 'created_at'], 'parents' => ['presale_estimate_id' => ['type' => 'presale_estimate', 'nullable' => true], 'presale_estimate_version_id' => ['type' => 'presale_estimate_version', 'nullable' => true, 'matches' => ['presale_estimate_id' => 'presale_estimate_id']], 'presale_estimate_section_id' => ['type' => 'presale_estimate_section', 'nullable' => true, 'matches' => ['presale_estimate_id' => 'presale_estimate_id']], 'budget_article_id' => ['type' => 'budget_article', 'nullable' => true], 'responsibility_center_id' => ['type' => 'responsibility_center', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => ['quantity', 'unit_cost', 'discount_amount', 'vat_rate', 'subtotal_amount', 'total_amount']],
            'presale_estimate_section' => ['model' => \App\BusinessModules\Features\PresaleEstimates\Models\PresaleEstimateSection::class, 'domain' => 'presale_estimates', 'source' => 'presale_estimates', 'module' => null, 'permissions' => ['presale_estimates.view'], 'fields' => ['id', 'organization_id', 'presale_estimate_id', 'presale_estimate_version_id', 'title', 'description', 'sort_order', 'updated_at', 'created_at'], 'parents' => ['presale_estimate_id' => ['type' => 'presale_estimate', 'nullable' => true], 'presale_estimate_version_id' => ['type' => 'presale_estimate_version', 'nullable' => true, 'matches' => ['presale_estimate_id' => 'presale_estimate_id']]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'presale_estimate_version' => ['model' => \App\BusinessModules\Features\PresaleEstimates\Models\PresaleEstimateVersion::class, 'domain' => 'presale_estimates', 'source' => 'presale_estimates', 'module' => null, 'permissions' => ['presale_estimates.view'], 'fields' => ['id', 'organization_id', 'presale_estimate_id', 'version_number', 'status', 'title', 'created_by_user_id', 'accepted_at', 'locked_at', 'updated_at', 'created_at'], 'parents' => ['presale_estimate_id' => ['type' => 'presale_estimate', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'commercial_proposal_approval' => ['model' => \App\BusinessModules\Features\CommercialProposals\Models\CommercialProposalApproval::class, 'domain' => 'commercial_proposals_business', 'source' => 'commercial_proposals_business', 'module' => 'commercial-proposals', 'permissions' => ['commercial_proposals.view'], 'fields' => ['id', 'organization_id', 'commercial_proposal_id', 'commercial_proposal_version_id', 'requested_by_user_id', 'decided_by_user_id', 'status', 'comment', 'requested_at', 'decided_at', 'updated_at', 'created_at'], 'parents' => ['commercial_proposal_id' => ['type' => 'commercial_proposal', 'nullable' => true], 'commercial_proposal_version_id' => ['type' => 'commercial_proposal_version', 'nullable' => true, 'matches' => ['commercial_proposal_id' => 'commercial_proposal_id']]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'commercial_proposal_export' => ['model' => \App\BusinessModules\Features\CommercialProposals\Models\CommercialProposalExport::class, 'domain' => 'commercial_proposals_business', 'source' => 'commercial_proposals_business', 'module' => 'commercial-proposals', 'permissions' => ['commercial_proposals.view'], 'fields' => ['id', 'organization_id', 'commercial_proposal_id', 'commercial_proposal_version_id', 'requested_by_user_id', 'format', 'status', 'generated_at', 'updated_at', 'created_at'], 'parents' => ['commercial_proposal_id' => ['type' => 'commercial_proposal', 'nullable' => true], 'commercial_proposal_version_id' => ['type' => 'commercial_proposal_version', 'nullable' => true, 'matches' => ['commercial_proposal_id' => 'commercial_proposal_id']]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'commercial_proposal_file' => ['model' => \App\BusinessModules\Features\CommercialProposals\Models\CommercialProposalFile::class, 'domain' => 'commercial_proposals_business', 'source' => 'commercial_proposals_business', 'module' => 'commercial-proposals', 'permissions' => ['commercial_proposals.view'], 'fields' => ['id', 'organization_id', 'commercial_proposal_id', 'commercial_proposal_version_id', 'uploaded_by_user_id', 'category', 'original_name', 'mime_type', 'size_bytes', 'updated_at', 'created_at'], 'parents' => ['commercial_proposal_id' => ['type' => 'commercial_proposal', 'nullable' => true], 'commercial_proposal_version_id' => ['type' => 'commercial_proposal_version', 'nullable' => true, 'matches' => ['commercial_proposal_id' => 'commercial_proposal_id']]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'commercial_proposal_line_item' => ['model' => \App\BusinessModules\Features\CommercialProposals\Models\CommercialProposalLineItem::class, 'domain' => 'commercial_proposals_business', 'source' => 'commercial_proposals_business', 'module' => 'commercial-proposals', 'permissions' => ['commercial_proposals.view'], 'fields' => ['id', 'organization_id', 'commercial_proposal_id', 'commercial_proposal_version_id', 'commercial_proposal_section_id', 'title', 'description', 'unit', 'quantity', 'unit_price', 'discount_amount', 'vat_rate', 'subtotal_amount', 'total_amount', 'sort_order', 'updated_at', 'created_at'], 'parents' => ['commercial_proposal_id' => ['type' => 'commercial_proposal', 'nullable' => true], 'commercial_proposal_version_id' => ['type' => 'commercial_proposal_version', 'nullable' => true, 'matches' => ['commercial_proposal_id' => 'commercial_proposal_id']], 'commercial_proposal_section_id' => ['type' => 'commercial_proposal_section', 'nullable' => true, 'matches' => ['commercial_proposal_id' => 'commercial_proposal_id']]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => ['quantity', 'unit_price', 'discount_amount', 'vat_rate', 'subtotal_amount', 'total_amount']],
            'commercial_proposal_section' => ['model' => \App\BusinessModules\Features\CommercialProposals\Models\CommercialProposalSection::class, 'domain' => 'commercial_proposals_business', 'source' => 'commercial_proposals_business', 'module' => 'commercial-proposals', 'permissions' => ['commercial_proposals.view'], 'fields' => ['id', 'organization_id', 'commercial_proposal_id', 'commercial_proposal_version_id', 'title', 'body', 'sort_order', 'updated_at', 'created_at'], 'parents' => ['commercial_proposal_id' => ['type' => 'commercial_proposal', 'nullable' => true], 'commercial_proposal_version_id' => ['type' => 'commercial_proposal_version', 'nullable' => true, 'matches' => ['commercial_proposal_id' => 'commercial_proposal_id']]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'commercial_proposal_sent_event' => ['model' => \App\BusinessModules\Features\CommercialProposals\Models\CommercialProposalSentEvent::class, 'domain' => 'commercial_proposals_business', 'source' => 'commercial_proposals_business', 'module' => 'commercial-proposals', 'permissions' => ['commercial_proposals.view'], 'fields' => ['id', 'organization_id', 'commercial_proposal_id', 'commercial_proposal_version_id', 'sent_by_user_id', 'channel', 'subject', 'message', 'sent_at', 'updated_at', 'created_at'], 'parents' => ['commercial_proposal_id' => ['type' => 'commercial_proposal', 'nullable' => true], 'commercial_proposal_version_id' => ['type' => 'commercial_proposal_version', 'nullable' => true, 'matches' => ['commercial_proposal_id' => 'commercial_proposal_id']]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'commercial_proposal_template' => ['model' => \App\BusinessModules\Features\CommercialProposals\Models\CommercialProposalTemplate::class, 'domain' => 'commercial_proposals_business', 'source' => 'commercial_proposals_business', 'module' => 'commercial-proposals', 'permissions' => ['commercial_proposals.templates.manage'], 'fields' => ['id', 'organization_id', 'code', 'name', 'description', 'is_default', 'is_active', 'updated_at', 'created_at'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'commercial_proposal_timeline_event' => ['model' => \App\BusinessModules\Features\CommercialProposals\Models\CommercialProposalTimelineEvent::class, 'domain' => 'commercial_proposals_business', 'source' => 'commercial_proposals_business', 'module' => 'commercial-proposals', 'permissions' => ['commercial_proposals.view'], 'fields' => ['id', 'organization_id', 'commercial_proposal_id', 'commercial_proposal_version_id', 'actor_user_id', 'event_type', 'from_status', 'to_status', 'occurred_at', 'updated_at', 'created_at'], 'parents' => ['commercial_proposal_id' => ['type' => 'commercial_proposal', 'nullable' => true], 'commercial_proposal_version_id' => ['type' => 'commercial_proposal_version', 'nullable' => true, 'matches' => ['commercial_proposal_id' => 'commercial_proposal_id']]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'commercial_proposal_version' => ['model' => \App\BusinessModules\Features\CommercialProposals\Models\CommercialProposalVersion::class, 'domain' => 'commercial_proposals_business', 'source' => 'commercial_proposals_business', 'module' => 'commercial-proposals', 'permissions' => ['commercial_proposals.view'], 'fields' => ['id', 'organization_id', 'commercial_proposal_id', 'version_number', 'status', 'title', 'created_by_user_id', 'submitted_at', 'approved_at', 'sent_at', 'customer_decision_at', 'locked_at', 'updated_at', 'created_at'], 'parents' => ['commercial_proposal_id' => ['type' => 'commercial_proposal', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'crm_contact_identity' => ['model' => \App\BusinessModules\Features\Crm\Models\CrmContactIdentity::class, 'domain' => 'crm_business', 'source' => 'crm_business', 'module' => 'crm', 'permissions' => ['crm.contacts.view', 'crm.companies.view'], 'fields' => ['id', 'organization_id', 'company_id', 'contact_id', 'identity_type', 'value', 'source', 'updated_at', 'created_at'], 'parents' => ['company_id' => ['type' => 'crm_company', 'nullable' => true], 'contact_id' => ['type' => 'crm_contact', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'crm_contact_point' => ['model' => \App\BusinessModules\Features\Crm\Models\CrmContactPoint::class, 'domain' => 'crm_business', 'source' => 'crm_business', 'module' => 'crm', 'permissions' => ['crm.contacts.view', 'crm.companies.view'], 'fields' => ['id', 'organization_id', 'company_id', 'contact_id', 'point_type', 'label', 'value', 'is_primary', 'is_verified', 'updated_at', 'created_at'], 'parents' => ['company_id' => ['type' => 'crm_company', 'nullable' => true], 'contact_id' => ['type' => 'crm_contact', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'crm_conversion_operation' => ['model' => \App\BusinessModules\Features\Crm\Models\CrmConversionOperation::class, 'domain' => 'crm_business', 'source' => 'crm_business', 'module' => 'crm', 'permissions' => ['crm.deals.view'], 'fields' => ['id', 'organization_id', 'crm_deal_id', 'tender_id', 'commercial_proposal_id', 'status', 'project_id', 'contract_id', 'error_code', 'created_by_user_id', 'completed_at', 'updated_at', 'created_at'], 'parents' => ['crm_deal_id' => ['type' => 'crm_deal', 'nullable' => true], 'tender_id' => ['type' => 'tender', 'nullable' => true], 'commercial_proposal_id' => ['type' => 'commercial_proposal', 'nullable' => true], 'contract_id' => ['type' => 'contract', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => 'project_id', 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'crm_import_batch' => ['model' => \App\BusinessModules\Features\Crm\Models\CrmImportBatch::class, 'domain' => 'crm_business', 'source' => 'crm_business', 'module' => 'crm', 'permissions' => ['crm.import.preview'], 'fields' => ['id', 'organization_id', 'entity_type', 'source_format', 'status', 'original_filename', 'total_rows', 'accepted_rows', 'warning_rows', 'blocked_rows', 'progress_percent', 'uploaded_by_user_id', 'confirmed_by_user_id', 'confirmed_at', 'cancelled_at', 'updated_at', 'created_at'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'crm_import_row' => ['model' => \App\BusinessModules\Features\Crm\Models\CrmImportRow::class, 'domain' => 'crm_business', 'source' => 'crm_business', 'module' => 'crm', 'permissions' => ['crm.import.preview'], 'fields' => ['id', 'batch_id', 'row_number', 'decision', 'status', 'created_entity_id', 'updated_at', 'created_at'], 'parents' => ['batch_id' => ['type' => 'crm_import_batch', 'nullable' => false]], 'organization_column' => null, 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'crm_merge_event' => ['model' => \App\BusinessModules\Features\Crm\Models\CrmMergeEvent::class, 'domain' => 'crm_business', 'source' => 'crm_business', 'module' => 'crm', 'permissions' => ['crm.merge.view'], 'fields' => ['id', 'organization_id', 'entity_type', 'master_id', 'duplicate_id', 'actor_user_id', 'reason', 'created_at'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['created_at'], 'numeric_fields' => []],
            'crm_pipeline' => ['model' => \App\BusinessModules\Features\Crm\Models\CrmPipeline::class, 'domain' => 'crm_business', 'source' => 'crm_business', 'module' => 'crm', 'permissions' => ['crm.view'], 'fields' => ['id', 'organization_id', 'code', 'label', 'entity_type', 'is_default', 'is_active', 'updated_at', 'created_at'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'crm_pipeline_stage' => ['model' => \App\BusinessModules\Features\Crm\Models\CrmPipelineStage::class, 'domain' => 'crm_business', 'source' => 'crm_business', 'module' => 'crm', 'permissions' => ['crm.view'], 'fields' => ['id', 'pipeline_id', 'code', 'label', 'category', 'sort_order', 'probability_percent', 'is_terminal', 'updated_at', 'created_at'], 'parents' => ['pipeline_id' => ['type' => 'crm_pipeline', 'nullable' => false]], 'organization_column' => null, 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'crm_source' => ['model' => \App\BusinessModules\Features\Crm\Models\CrmSource::class, 'domain' => 'crm_business', 'source' => 'crm_business', 'module' => 'crm', 'permissions' => ['crm.view'], 'fields' => ['id', 'organization_id', 'code', 'label', 'channel_type', 'is_active', 'created_by_user_id', 'updated_by_user_id', 'updated_at', 'created_at'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'crm_timeline_event' => ['model' => \App\BusinessModules\Features\Crm\Models\CrmTimelineEvent::class, 'domain' => 'crm_business', 'source' => 'crm_business', 'module' => 'crm', 'permissions' => ['crm.timeline.view'], 'fields' => ['id', 'organization_id', 'actor_user_id', 'entity_type', 'entity_id', 'event_type', 'summary', 'created_at'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['created_at'], 'numeric_fields' => []],
            'external_supplier_contact' => ['model' => \App\BusinessModules\Features\Procurement\Models\ExternalSupplierContact::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.purchase_orders.view'], 'fields' => ['id', 'organization_id', 'name', 'contact_person', 'phone', 'email', 'tax_number', 'address', 'updated_at', 'created_at'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'procurement_approval_policy' => ['model' => \App\BusinessModules\Features\Procurement\Models\ProcurementApprovalPolicy::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.settings.view'], 'fields' => ['id', 'organization_id', 'non_lowest_delta_amount', 'non_lowest_delta_percent', 'budget_exceed_amount', 'external_supplier_requires_identity', 'prevent_requester_approval', 'prevent_selector_approval', 'prevent_intake_author_approval', 'is_active', 'updated_at', 'created_at'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => ['non_lowest_delta_amount', 'non_lowest_delta_percent', 'budget_exceed_amount']],
            'purchase_order_item' => ['model' => \App\BusinessModules\Features\Procurement\Models\PurchaseOrderItem::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.purchase_orders.view'], 'fields' => ['id', 'purchase_order_id', 'purchase_request_line_id', 'supplier_request_line_id', 'supplier_proposal_line_id', 'material_id', 'material_name', 'quantity', 'unit', 'unit_price', 'total_price', 'notes', 'updated_at', 'created_at'], 'parents' => ['purchase_order_id' => ['type' => 'purchase_order', 'nullable' => false], 'purchase_request_line_id' => ['type' => 'purchase_request_line', 'nullable' => true], 'supplier_request_line_id' => ['type' => 'supplier_request_line', 'nullable' => true], 'supplier_proposal_line_id' => ['type' => 'supplier_proposal_line', 'nullable' => true], 'material_id' => ['type' => 'material', 'nullable' => true]], 'organization_column' => null, 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => ['quantity', 'unit_price', 'total_price']],
            'purchase_receipt_document' => ['model' => \App\BusinessModules\Features\Procurement\Models\PurchaseReceiptDocument::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.purchase_orders.view'], 'fields' => ['id', 'organization_id', 'purchase_order_id', 'purchase_receipt_id', 'uploaded_by_user_id', 'document_type', 'status', 'original_name', 'mime_type', 'size_bytes', 'format_version', 'document_function', 'document_number', 'document_date', 'seller_inn', 'buyer_inn', 'currency_code', 'validated_at', 'attached_at', 'updated_at', 'created_at'], 'parents' => ['purchase_order_id' => ['type' => 'purchase_order', 'nullable' => false], 'purchase_receipt_id' => ['type' => 'purchase_receipt', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'purchase_receipt_inventory_lot' => ['model' => \App\BusinessModules\Features\Procurement\Models\PurchaseReceiptInventoryLot::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.purchase_orders.view'], 'fields' => ['id', 'organization_id', 'purchase_receipt_line_id', 'warehouse_balance_id', 'receipt_warehouse_movement_id', 'original_quantity', 'reversed_quantity', 'returned_quantity', 'unit_dimension', 'unit_code', 'conversion_version', 'updated_at', 'created_at'], 'parents' => ['purchase_receipt_line_id' => ['type' => 'purchase_receipt_line', 'nullable' => false], 'warehouse_balance_id' => ['type' => 'warehouse_balance', 'nullable' => true], 'receipt_warehouse_movement_id' => ['type' => 'warehouse_movement', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => ['original_quantity', 'reversed_quantity', 'returned_quantity']],
            'purchase_receipt_line' => ['model' => \App\BusinessModules\Features\Procurement\Models\PurchaseReceiptLine::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.purchase_orders.view'], 'fields' => ['id', 'purchase_receipt_id', 'purchase_order_item_id', 'quantity_received', 'price', 'total_amount', 'reversed_at', 'reversed_by_user_id', 'reversal_reason_code', 'reversal_warehouse_movement_id', 'updated_at', 'created_at'], 'parents' => ['purchase_receipt_id' => ['type' => 'purchase_receipt', 'nullable' => false], 'purchase_order_item_id' => ['type' => 'purchase_order_item', 'nullable' => false], 'reversal_warehouse_movement_id' => ['type' => 'warehouse_movement', 'nullable' => true]], 'organization_column' => null, 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => ['quantity_received', 'price', 'total_amount']],
            'purchase_receipt_return' => ['model' => \App\BusinessModules\Features\Procurement\Models\PurchaseReceiptReturn::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.purchase_orders.view'], 'fields' => ['id', 'organization_id', 'purchase_receipt_line_id', 'warehouse_movement_id', 'supply_lifecycle_event_id', 'source_type', 'source_id', 'source_version', 'quantity', 'reason_code', 'actor_id', 'occurred_at', 'updated_at', 'created_at'], 'parents' => ['purchase_receipt_line_id' => ['type' => 'purchase_receipt_line', 'nullable' => false], 'warehouse_movement_id' => ['type' => 'warehouse_movement', 'nullable' => true], 'supply_lifecycle_event_id' => ['type' => 'supply_lifecycle_event', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => ['quantity']],
            'purchase_request_line' => ['model' => \App\BusinessModules\Features\Procurement\Models\PurchaseRequestLine::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.purchase_requests.view'], 'fields' => ['id', 'purchase_request_id', 'material_id', 'name', 'quantity', 'unit', 'specification', 'needed_by', 'updated_at', 'created_at'], 'parents' => ['purchase_request_id' => ['type' => 'purchase_request', 'nullable' => false], 'material_id' => ['type' => 'material', 'nullable' => true]], 'organization_column' => null, 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => ['quantity']],
            'supplier_party' => ['model' => \App\BusinessModules\Features\Procurement\Models\SupplierParty::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.purchase_orders.view'], 'fields' => ['id', 'organization_id', 'type', 'status', 'registered_supplier_id', 'external_supplier_contact_id', 'display_name', 'contact_name', 'email', 'phone', 'tax_id', 'linked_at', 'updated_at', 'created_at'], 'parents' => ['registered_supplier_id' => ['type' => 'supplier', 'nullable' => true], 'external_supplier_contact_id' => ['type' => 'external_supplier_contact', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'supplier_proposal_intake' => ['model' => \App\BusinessModules\Features\Procurement\Models\SupplierProposalIntake::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.supplier_proposals.view'], 'fields' => ['id', 'organization_id', 'supplier_proposal_id', 'supplier_party_id', 'source', 'received_at', 'entered_by', 'comment', 'updated_at', 'created_at'], 'parents' => ['supplier_proposal_id' => ['type' => 'supplier_proposal', 'nullable' => false], 'supplier_party_id' => ['type' => 'supplier_party', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'supplier_proposal_line' => ['model' => \App\BusinessModules\Features\Procurement\Models\SupplierProposalLine::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.supplier_proposals.view'], 'fields' => ['id', 'supplier_proposal_id', 'supplier_request_line_id', 'material_id', 'name', 'quantity', 'unit', 'unit_price', 'total_amount', 'comment', 'updated_at', 'created_at'], 'parents' => ['supplier_proposal_id' => ['type' => 'supplier_proposal', 'nullable' => false], 'supplier_request_line_id' => ['type' => 'supplier_request_line', 'nullable' => true], 'material_id' => ['type' => 'material', 'nullable' => true]], 'organization_column' => null, 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => ['quantity', 'unit_price', 'total_amount']],
            'supplier_proposal_version' => ['model' => \App\BusinessModules\Features\Procurement\Models\SupplierProposalVersion::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.supplier_proposals.view'], 'fields' => ['id', 'organization_id', 'supplier_proposal_id', 'version_number', 'integrity_status', 'created_by', 'created_at'], 'parents' => ['supplier_proposal_id' => ['type' => 'supplier_proposal', 'nullable' => false]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['created_at'], 'numeric_fields' => []],
            'supplier_request_line' => ['model' => \App\BusinessModules\Features\Procurement\Models\SupplierRequestLine::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.supplier_requests.view'], 'fields' => ['id', 'supplier_request_id', 'purchase_request_line_id', 'material_id', 'name', 'quantity', 'unit', 'specification', 'updated_at', 'created_at'], 'parents' => ['supplier_request_id' => ['type' => 'supplier_request', 'nullable' => false], 'purchase_request_line_id' => ['type' => 'purchase_request_line', 'nullable' => true], 'material_id' => ['type' => 'material', 'nullable' => true]], 'organization_column' => null, 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => ['quantity']],
            'supplier_request_version' => ['model' => \App\BusinessModules\Features\Procurement\Models\SupplierRequestVersion::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.supplier_requests.view'], 'fields' => ['id', 'organization_id', 'supplier_request_id', 'version_number', 'integrity_status', 'sent_by', 'sent_at', 'updated_at', 'created_at'], 'parents' => ['supplier_request_id' => ['type' => 'supplier_request', 'nullable' => false]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['updated_at', 'created_at'], 'numeric_fields' => []],
            'procurement_award_evidence_event' => ['model' => \App\BusinessModules\Features\Procurement\Reporting\Award\Models\ProcurementAwardEvidenceEvent::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.supplier_proposals.view', 'procurement.proposal_decisions.view'], 'fields' => ['id', 'organization_id', 'project_id', 'purchase_request_id', 'supplier_request_id', 'supplier_request_version_id', 'decision_id', 'decision_revision', 'event_sequence', 'event_type', 'occurred_at', 'actor_id', 'selected_status', 'policy_id', 'policy_version', 'candidate_count', 'comparable_count', 'completeness', 'selected_proposal_id', 'selected_proposal_version_id', 'cheapest_proposal_id', 'cheapest_proposal_version_id', 'selected_rank', 'cheapest_rank', 'reason_present', 'reason_normalized_length', 'predecessor_event_id', 'purchase_order_id', 'created_at'], 'parents' => ['purchase_request_id' => ['type' => 'purchase_request', 'nullable' => false], 'supplier_request_id' => ['type' => 'supplier_request', 'nullable' => false], 'supplier_request_version_id' => ['type' => 'supplier_request_version', 'nullable' => true], 'decision_id' => ['type' => 'supplier_proposal_decision', 'nullable' => false], 'selected_proposal_id' => ['type' => 'supplier_proposal', 'nullable' => false], 'selected_proposal_version_id' => ['type' => 'supplier_proposal_version', 'nullable' => true], 'cheapest_proposal_id' => ['type' => 'supplier_proposal', 'nullable' => true], 'cheapest_proposal_version_id' => ['type' => 'supplier_proposal_version', 'nullable' => true], 'purchase_order_id' => ['type' => 'purchase_order', 'nullable' => true], 'predecessor_event_id' => ['type' => 'procurement_award_evidence_event', 'nullable' => true, 'reference_only' => true]], 'organization_column' => 'organization_id', 'project_column' => 'project_id', 'version_columns' => ['created_at'], 'numeric_fields' => []],
            'supplier_award_decision_version' => ['model' => \App\BusinessModules\Features\Procurement\Reporting\Award\Models\SupplierAwardDecisionVersion::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.supplier_proposals.view', 'procurement.proposal_decisions.view'], 'fields' => ['id', 'organization_id', 'decision_id', 'decision_version', 'purchase_request_id', 'project_id', 'selected_supplier_party_id', 'supplier_request_id', 'selected_proposal_version_id', 'cheapest_proposal_version_id', 'median_proposal_version_id', 'is_lowest_price_selected', 'decision_reason', 'selected_by', 'selected_at', 'recorded_at'], 'parents' => ['decision_id' => ['type' => 'supplier_proposal_decision', 'nullable' => false], 'purchase_request_id' => ['type' => 'purchase_request', 'nullable' => false], 'selected_supplier_party_id' => ['type' => 'supplier_party', 'nullable' => false], 'supplier_request_id' => ['type' => 'supplier_request', 'nullable' => false], 'selected_proposal_version_id' => ['type' => 'supplier_proposal_version', 'nullable' => true], 'cheapest_proposal_version_id' => ['type' => 'supplier_proposal_version', 'nullable' => true], 'median_proposal_version_id' => ['type' => 'supplier_proposal_version', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => 'project_id', 'version_columns' => ['recorded_at'], 'numeric_fields' => []],
            'supplier_award_row' => ['model' => \App\BusinessModules\Features\Procurement\Reporting\Award\Models\SupplierAwardRow::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.supplier_proposals.view', 'procurement.proposal_decisions.view'], 'fields' => ['id', 'organization_id', 'snapshot_id', 'row_key', 'project_id', 'decision_id', 'decision_version', 'proposal_version_id', 'supplier_party_id', 'selected_proposal_version_id', 'cheapest_proposal_version_id', 'median_proposal_version_id', 'invited_count', 'responded_count', 'currency', 'selected_amount_minor', 'cheapest_amount_minor', 'median_amount_minor', 'premium_minor', 'premium_ratio', 'median_variance_minor', 'median_variance_ratio', 'participation_ratio', 'non_lowest_selected', 'decision_reason', 'selected_at'], 'parents' => ['decision_id' => ['type' => 'supplier_proposal_decision', 'nullable' => false], 'proposal_version_id' => ['type' => 'supplier_proposal_version', 'nullable' => false], 'supplier_party_id' => ['type' => 'supplier_party', 'nullable' => false], 'selected_proposal_version_id' => ['type' => 'supplier_proposal_version', 'nullable' => true], 'cheapest_proposal_version_id' => ['type' => 'supplier_proposal_version', 'nullable' => true], 'median_proposal_version_id' => ['type' => 'supplier_proposal_version', 'nullable' => true], 'snapshot_id' => ['type' => 'supplier_award_snapshot', 'nullable' => false]], 'organization_column' => 'organization_id', 'project_column' => 'project_id', 'version_columns' => [], 'numeric_fields' => ['median_amount_minor', 'median_variance_minor', 'selected_amount_minor', 'cheapest_amount_minor', 'premium_minor', 'premium_ratio', 'median_variance_ratio', 'participation_ratio']],
            'supplier_award_snapshot' => ['model' => \App\BusinessModules\Features\Procurement\Reporting\Award\Models\SupplierAwardSnapshot::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.supplier_proposals.view', 'procurement.proposal_decisions.view'], 'fields' => ['id', 'organization_id', 'formula_version', 'source_schema_version', 'as_of', 'generated_at', 'stale_at', 'row_count', 'eligible_count', 'gap_count', 'quality_status', 'reconciliation_status'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['generated_at'], 'numeric_fields' => []],
            'procurement_cycle_owner_expectation_version' => ['model' => \App\BusinessModules\Features\Procurement\Reporting\Cycle\Models\ProcurementCycleOwnerExpectationVersion::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.dashboard.view'], 'fields' => ['id', 'organization_id', 'purchase_request_id', 'purchase_request_line_id', 'expectation_version', 'effective_from', 'source_event_id', 'recorded_at'], 'parents' => ['purchase_request_id' => ['type' => 'purchase_request', 'nullable' => false], 'purchase_request_line_id' => ['type' => 'purchase_request_line', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['recorded_at'], 'numeric_fields' => []],
            'procurement_cycle_policy_version' => ['model' => \App\BusinessModules\Features\Procurement\Reporting\Cycle\Models\ProcurementCyclePolicyVersion::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.dashboard.view'], 'fields' => ['id', 'organization_id', 'project_id', 'version_number', 'formula_version', 'source_schema_version', 'event_schema_version', 'calendar_version', 'timezone', 'total_sla_seconds', 'effective_from', 'effective_to', 'published_by', 'published_at', 'created_at'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => 'project_id', 'version_columns' => ['created_at'], 'numeric_fields' => []],
            'procurement_cycle_row' => ['model' => \App\BusinessModules\Features\Procurement\Reporting\Cycle\Models\ProcurementCycleRow::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.dashboard.view'], 'fields' => ['id', 'organization_id', 'snapshot_id', 'row_key', 'purchase_request_id', 'purchase_request_line_id', 'project_id', 'supplier_request_id', 'supplier_proposal_version_id', 'purchase_order_id', 'purchase_receipt_id', 'stage', 'stage_started_at', 'closed_at', 'cohort_date', 'outcome_cohort_date', 'cohort_mature', 'outcome_code', 'total_duration_seconds', 'sla_numerator', 'sla_denominator'], 'parents' => ['purchase_request_id' => ['type' => 'purchase_request', 'nullable' => false], 'purchase_request_line_id' => ['type' => 'purchase_request_line', 'nullable' => true], 'supplier_request_id' => ['type' => 'supplier_request', 'nullable' => true], 'supplier_proposal_version_id' => ['type' => 'supplier_proposal_version', 'nullable' => true], 'purchase_order_id' => ['type' => 'purchase_order', 'nullable' => true], 'purchase_receipt_id' => ['type' => 'purchase_receipt', 'nullable' => true], 'snapshot_id' => ['type' => 'procurement_cycle_snapshot', 'nullable' => false]], 'organization_column' => 'organization_id', 'project_column' => 'project_id', 'version_columns' => [], 'numeric_fields' => []],
            'procurement_cycle_snapshot' => ['model' => \App\BusinessModules\Features\Procurement\Reporting\Cycle\Models\ProcurementCycleSnapshot::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.dashboard.view'], 'fields' => ['id', 'organization_id', 'formula_version', 'source_schema_version', 'policy_version_id', 'as_of', 'generated_at', 'stale_at', 'row_count', 'eligible_count', 'sla_numerator', 'gap_count', 'quality_status', 'reconciliation_status'], 'parents' => ['policy_version_id' => ['type' => 'procurement_cycle_policy_version', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['generated_at'], 'numeric_fields' => []],
            'procurement_process_event' => ['model' => \App\BusinessModules\Features\Procurement\Reporting\Cycle\Models\ProcurementProcessEvent::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.dashboard.view'], 'fields' => ['id', 'organization_id', 'project_id', 'purchase_request_id', 'purchase_request_line_id', 'supplier_request_id', 'supplier_request_line_id', 'supplier_party_id', 'supplier_proposal_id', 'supplier_proposal_version_id', 'supplier_proposal_decision_id', 'purchase_order_id', 'purchase_order_item_id', 'purchase_receipt_id', 'purchase_receipt_line_id', 'policy_version_id', 'calendar_version', 'event_code', 'terminal_reason', 'event_version', 'actor_id', 'occurred_at', 'source_kind', 'source_id', 'source_event_id', 'created_at'], 'parents' => ['purchase_request_id' => ['type' => 'purchase_request', 'nullable' => false], 'purchase_request_line_id' => ['type' => 'purchase_request_line', 'nullable' => true], 'supplier_request_id' => ['type' => 'supplier_request', 'nullable' => true], 'supplier_request_line_id' => ['type' => 'supplier_request_line', 'nullable' => true], 'supplier_party_id' => ['type' => 'supplier_party', 'nullable' => true], 'supplier_proposal_id' => ['type' => 'supplier_proposal', 'nullable' => true], 'supplier_proposal_version_id' => ['type' => 'supplier_proposal_version', 'nullable' => true], 'supplier_proposal_decision_id' => ['type' => 'supplier_proposal_decision', 'nullable' => true], 'purchase_order_id' => ['type' => 'purchase_order', 'nullable' => true], 'purchase_order_item_id' => ['type' => 'purchase_order_item', 'nullable' => true], 'purchase_receipt_id' => ['type' => 'purchase_receipt', 'nullable' => true], 'purchase_receipt_line_id' => ['type' => 'purchase_receipt_line', 'nullable' => true], 'policy_version_id' => ['type' => 'procurement_cycle_policy_version', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => 'project_id', 'version_columns' => ['created_at'], 'numeric_fields' => []],
            'purchase_order_promise_version' => ['model' => \App\BusinessModules\Features\Procurement\Reporting\Supply\Models\PurchaseOrderPromiseVersion::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.purchase_orders.view'], 'fields' => ['id', 'organization_id', 'purchase_order_id', 'purchase_order_item_id', 'promise_version', 'supplier_id', 'project_id', 'warehouse_id', 'material_id', 'buyer_id', 'priority', 'ordered_quantity', 'ordered_value_minor', 'value_basis', 'unit_dimension', 'unit_code', 'conversion_version', 'promised_at', 'promise_timezone', 'currency', 'currency_source', 'tax_basis', 'freight_basis', 'source_version', 'supersedes_id', 'effective_from', 'effective_to', 'recorded_at'], 'parents' => ['purchase_order_id' => ['type' => 'purchase_order', 'nullable' => false], 'purchase_order_item_id' => ['type' => 'purchase_order_item', 'nullable' => false], 'supplier_id' => ['type' => 'supplier', 'nullable' => true], 'warehouse_id' => ['type' => 'warehouse', 'nullable' => true], 'material_id' => ['type' => 'material', 'nullable' => true], 'supersedes_id' => ['type' => 'purchase_order_promise_version', 'nullable' => true, 'reference_only' => true]], 'organization_column' => 'organization_id', 'project_column' => 'project_id', 'version_columns' => ['recorded_at'], 'numeric_fields' => ['ordered_quantity', 'ordered_value_minor']],
            'sent_purchase_order_line_owner' => ['model' => \App\BusinessModules\Features\Procurement\Reporting\Supply\Models\SentPurchaseOrderLineOwner::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.purchase_orders.view'], 'fields' => ['id', 'organization_id', 'purchase_order_id', 'purchase_order_item_id', 'source_version', 'purchase_request_id', 'purchase_request_line_id', 'project_id', 'supplier_id', 'warehouse_id', 'material_id', 'buyer_id', 'priority', 'unit_dimension', 'unit_code', 'conversion_version', 'effective_from', 'recorded_at'], 'parents' => ['purchase_order_id' => ['type' => 'purchase_order', 'nullable' => false], 'purchase_order_item_id' => ['type' => 'purchase_order_item', 'nullable' => false], 'purchase_request_id' => ['type' => 'purchase_request', 'nullable' => false], 'purchase_request_line_id' => ['type' => 'purchase_request_line', 'nullable' => true], 'supplier_id' => ['type' => 'supplier', 'nullable' => true], 'warehouse_id' => ['type' => 'warehouse', 'nullable' => true], 'material_id' => ['type' => 'material', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => 'project_id', 'version_columns' => ['recorded_at'], 'numeric_fields' => []],
            'supply_lifecycle_event' => ['model' => \App\BusinessModules\Features\Procurement\Reporting\Supply\Models\SupplyLifecycleEvent::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.purchase_orders.view'], 'fields' => ['id', 'organization_id', 'purchase_order_id', 'purchase_order_item_id', 'promise_version_id', 'event_type', 'source_type', 'source_id', 'source_version', 'signed_quantity', 'unit_dimension', 'unit_code', 'conversion_version', 'occurred_at', 'reversed_event_id', 'reason_code', 'recorded_at'], 'parents' => ['purchase_order_id' => ['type' => 'purchase_order', 'nullable' => false], 'purchase_order_item_id' => ['type' => 'purchase_order_item', 'nullable' => false], 'promise_version_id' => ['type' => 'purchase_order_promise_version', 'nullable' => true], 'reversed_event_id' => ['type' => 'supply_lifecycle_event', 'nullable' => true, 'reference_only' => true]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['recorded_at', 'occurred_at'], 'numeric_fields' => ['signed_quantity']],
            'supply_reliability_policy_version' => ['model' => \App\BusinessModules\Features\Procurement\Reporting\Supply\Models\SupplyReliabilityPolicyVersion::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.purchase_orders.view'], 'fields' => ['id', 'organization_id', 'policy_version', 'on_time_cutoff_seconds', 'quantity_tolerance', 'exclude_cancellation_before_send', 'maturity_seconds', 'freshness_ttl_seconds', 'effective_from', 'effective_to', 'created_at'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['created_at'], 'numeric_fields' => []],
            'supply_reliability_row' => ['model' => \App\BusinessModules\Features\Procurement\Reporting\Supply\Models\SupplyReliabilityRow::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.purchase_orders.view'], 'fields' => ['id', 'organization_id', 'snapshot_id', 'row_key', 'purchase_order_id', 'purchase_order_item_id', 'promise_version_id', 'supplier_id', 'project_id', 'warehouse_id', 'material_id', 'original_promised_at', 'promised_month', 'delay_bucket', 'ordered_quantity', 'net_received_quantity', 'unit_dimension', 'unit_code', 'conversion_version', 'first_qualifying_receipt_at', 'cancelled_at', 'eligible', 'on_time', 'in_full', 'stable_in_full', 'mature', 'otif', 'otif_numerator', 'eligible_denominator', 'quantity_otif_numerator', 'quantity_otif_denominator', 'value_otif_numerator_minor', 'value_otif_denominator_minor', 'value_currency', 'value_basis'], 'parents' => ['purchase_order_id' => ['type' => 'purchase_order', 'nullable' => false], 'purchase_order_item_id' => ['type' => 'purchase_order_item', 'nullable' => false], 'promise_version_id' => ['type' => 'purchase_order_promise_version', 'nullable' => false], 'supplier_id' => ['type' => 'supplier', 'nullable' => true], 'warehouse_id' => ['type' => 'warehouse', 'nullable' => true], 'material_id' => ['type' => 'material', 'nullable' => true], 'snapshot_id' => ['type' => 'supply_reliability_snapshot', 'nullable' => false]], 'organization_column' => 'organization_id', 'project_column' => 'project_id', 'version_columns' => [], 'numeric_fields' => ['ordered_quantity', 'net_received_quantity', 'value_otif_numerator_minor', 'value_otif_denominator_minor']],
            'supply_reliability_snapshot' => ['model' => \App\BusinessModules\Features\Procurement\Reporting\Supply\Models\SupplyReliabilitySnapshot::class, 'domain' => 'procurement_business', 'source' => 'procurement_business', 'module' => 'procurement', 'permissions' => ['procurement.purchase_orders.view'], 'fields' => ['id', 'organization_id', 'formula_version', 'source_schema_version', 'policy_version_id', 'as_of', 'generated_at', 'stale_at', 'row_count', 'eligible_count', 'otif_numerator', 'gap_count', 'quality_status', 'reconciliation_status'], 'parents' => ['policy_version_id' => ['type' => 'supply_reliability_policy_version', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null, 'version_columns' => ['generated_at'], 'numeric_fields' => []],
        ];
    }

    public static function anchorDefinitions(): array
    {
        return [
            'purchase_request' => ['model' => \App\BusinessModules\Features\Procurement\Models\PurchaseRequest::class, 'fields' => ['id', 'organization_id', 'site_request_id'], 'parents' => ['site_request_id' => ['type' => 'site_request', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null],
            'supplier_request' => ['model' => \App\BusinessModules\Features\Procurement\Models\SupplierRequest::class, 'fields' => ['id', 'organization_id', 'purchase_request_id'], 'parents' => ['purchase_request_id' => ['type' => 'purchase_request', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null],
            'supplier_proposal' => ['model' => \App\BusinessModules\Features\Procurement\Models\SupplierProposal::class, 'fields' => ['id', 'organization_id', 'supplier_request_id'], 'parents' => ['supplier_request_id' => ['type' => 'supplier_request', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null],
            'supplier_proposal_decision' => ['model' => \App\BusinessModules\Features\Procurement\Models\SupplierProposalDecision::class, 'fields' => ['id', 'organization_id', 'supplier_request_id'], 'parents' => ['supplier_request_id' => ['type' => 'supplier_request', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null],
            'purchase_order' => ['model' => \App\BusinessModules\Features\Procurement\Models\PurchaseOrder::class, 'fields' => ['id', 'organization_id', 'purchase_request_id', 'contract_id'], 'parents' => ['purchase_request_id' => ['type' => 'purchase_request', 'nullable' => true], 'contract_id' => ['type' => 'contract', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null],
            'purchase_receipt' => ['model' => \App\BusinessModules\Features\Procurement\Models\PurchaseReceipt::class, 'fields' => ['id', 'organization_id', 'warehouse_id'], 'parents' => ['warehouse_id' => ['type' => 'warehouse', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null],
            'crm_company' => ['model' => \App\BusinessModules\Features\Crm\Models\CrmCompany::class, 'fields' => ['id', 'organization_id'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null],
            'crm_contact' => ['model' => \App\BusinessModules\Features\Crm\Models\CrmContact::class, 'fields' => ['id', 'organization_id', 'company_id'], 'parents' => ['company_id' => ['type' => 'crm_company', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null],
            'crm_deal' => ['model' => \App\BusinessModules\Features\Crm\Models\CrmDeal::class, 'fields' => ['id', 'organization_id', 'project_id', 'contract_id', 'company_id'], 'parents' => ['contract_id' => ['type' => 'contract', 'nullable' => true], 'company_id' => ['type' => 'crm_company', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => 'project_id'],
            'crm_lead' => ['model' => \App\BusinessModules\Features\Crm\Models\CrmLead::class, 'fields' => ['id', 'organization_id', 'company_id', 'contact_id'], 'parents' => ['company_id' => ['type' => 'crm_company', 'nullable' => true], 'contact_id' => ['type' => 'crm_contact', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null],
            'crm_activity' => ['model' => \App\BusinessModules\Features\Crm\Models\CrmActivity::class, 'fields' => ['id', 'organization_id', 'company_id', 'contact_id'], 'parents' => ['company_id' => ['type' => 'crm_company', 'nullable' => true], 'contact_id' => ['type' => 'crm_contact', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null],
            'commercial_proposal' => ['model' => \App\BusinessModules\Features\CommercialProposals\Models\CommercialProposal::class, 'fields' => ['id', 'organization_id', 'project_id', 'crm_deal_id', 'contract_id'], 'parents' => ['contract_id' => ['type' => 'contract', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => 'project_id'],
            'tender' => ['model' => \App\BusinessModules\Features\Tenders\Models\Tender::class, 'fields' => ['id', 'organization_id', 'project_id', 'commercial_proposal_id', 'crm_deal_id', 'contract_id'], 'parents' => ['contract_id' => ['type' => 'contract', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => 'project_id'],
            'budget_version' => ['model' => \App\BusinessModules\Features\Budgeting\Models\BudgetVersion::class, 'fields' => ['id', 'organization_id'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null],
            'budget_article' => ['model' => \App\BusinessModules\Features\Budgeting\Models\BudgetArticle::class, 'fields' => ['id', 'organization_id'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null],
            'responsibility_center' => ['model' => \App\BusinessModules\Features\Budgeting\Models\ResponsibilityCenter::class, 'fields' => ['id', 'organization_id'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null],
            'contract' => ['model' => \App\Models\Contract::class, 'fields' => ['id', 'organization_id', 'project_id'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => 'project_id'],
            'supplier' => ['model' => \App\Models\Supplier::class, 'fields' => ['id', 'organization_id'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null],
            'material' => ['model' => \App\Models\Material::class, 'fields' => ['id', 'organization_id'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => null],
            'warehouse' => ['model' => \App\BusinessModules\Features\BasicWarehouse\Models\OrganizationWarehouse::class, 'fields' => ['id', 'organization_id', 'project_id'], 'parents' => [], 'organization_column' => 'organization_id', 'project_column' => 'project_id'],
            'warehouse_balance' => ['model' => \App\BusinessModules\Features\BasicWarehouse\Models\WarehouseBalance::class, 'fields' => ['id', 'organization_id', 'warehouse_id', 'material_id'], 'parents' => ['warehouse_id' => ['type' => 'warehouse', 'nullable' => true], 'material_id' => ['type' => 'material', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => null],
            'warehouse_movement' => ['model' => \App\BusinessModules\Features\BasicWarehouse\Models\WarehouseMovement::class, 'fields' => ['id', 'organization_id', 'project_id', 'warehouse_id', 'material_id'], 'parents' => ['warehouse_id' => ['type' => 'warehouse', 'nullable' => true], 'material_id' => ['type' => 'material', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => 'project_id'],
            'site_request' => ['model' => \App\BusinessModules\Features\SiteRequests\Models\SiteRequest::class, 'fields' => ['id', 'organization_id', 'project_id', 'material_id'], 'parents' => ['material_id' => ['type' => 'material', 'nullable' => true]], 'organization_column' => 'organization_id', 'project_column' => 'project_id'],
        ];
    }

    public static function parentProjectedModels(): array
    {
        return [\App\BusinessModules\Features\Procurement\Reporting\Award\Models\ProcurementAwardPolicyVersion::class => 'procurement_award_evidence_event.award_policy', \App\BusinessModules\Features\Procurement\Reporting\Award\Models\ProcurementAwardEvidenceCandidate::class => 'procurement_award_evidence_event.award_candidates'];
    }

    public static function inventory(): array
    {
        return array_map(static fn (array $record): array => ['model' => $record['model'], 'fields' => $record['fields']], self::recordDefinitions());
    }

    public static function scopeDefinitions(): array
    {
        return array_replace(self::anchorDefinitions(), self::recordDefinitions());
    }

    public static function entityDefinitions(): array
    {
        return array_map(static fn (array $record): array => [$record['source'], $record['model'], $record['domain']], self::recordDefinitions());
    }

    public static function entityPermissions(): array
    {
        $permissions = array_map(static fn (array $record): array => $record['permissions'], self::recordDefinitions());
        foreach ($permissions as $type => &$required) {
            if (str_starts_with($type, 'supplier_award') || str_starts_with($type, 'procurement_award')) { $required = ['procurement.supplier_proposals.view', 'procurement.proposal_decisions.view']; }
            elseif (str_starts_with($type, 'procurement_cycle') || $type === 'procurement_process_event') { $required = ['procurement.dashboard.view']; }
            elseif (str_starts_with($type, 'supply_') || $type === 'purchase_order_promise_version' || $type === 'sent_purchase_order_line_owner') { $required = ['procurement.purchase_orders.view']; }
        }
        unset($required);
        $permissions['crm_contact_identity'] = [];
        $permissions['crm_contact_point'] = [];
        return $permissions;
    }

    public static function parentColumns(): array
    {
        return array_map(static fn (array $record): array => $record['parents'], self::recordDefinitions());
    }

    public static function organizationColumns(): array
    {
        return array_replace(array_map(static fn (array $record): ?string => $record['organization_column'], self::recordDefinitions()), ['marketplace_contractor_profile' => null, 'marketplace_hiring_offer' => null]);
    }

    public static function organizationNullableCatalogs(): array
    {
        return ['crm_pipeline' => true, 'crm_source' => true];
    }

    public static function globalCatalogEntities(): array
    {
        return ['marketplace_work_category' => true];
    }

    public static function customOrganizationScopes(): array
    {
        return ['marketplace_contractor_profile' => true, 'marketplace_hiring_offer' => true];
    }

    public static function organizationAggregates(): array
    {
        return array_fill_keys(['contractor_scorecard_snapshot', 'contractor_scorecard_policy_version', 'procurement_cycle_snapshot', 'supplier_award_snapshot', 'supply_reliability_snapshot'], true);
    }

    public static function sourcePermissions(): array
    {
        return ['sales_supplier_catalog' => [], 'procurement_business' => ['finance.view'], 'crm_business' => [], 'commercial_proposals_business' => ['commercial_proposals.amounts.view'], 'presale_estimates' => ['presale_estimates.amounts.view'], 'contractor_marketplace' => ['finance.view']];
    }

    public static function domainGates(): array
    {
        $gates = [];
        foreach (self::recordDefinitions() as $type => $record) {
            if (isset(self::availabilityDefinitions()[$type])) { continue; }
            $gates[$record['domain']] ??= [$record['module'], []];
            $gates[$record['domain']][1] = array_values(array_unique([...$gates[$record['domain']][1], ...self::entityPermissions()[$type]]));
        }
        $gates['crm_business'][1] = array_values(array_unique([...$gates['crm_business'][1], 'crm.contacts.view', 'crm.companies.view']));
        return $gates;
    }

    public static function sourceClasses(): array
    {
        return [\App\BusinessModules\Features\AIAssistant\Services\Rag\Sources\ProcurementBusinessRagSource::class, \App\BusinessModules\Features\AIAssistant\Services\Rag\Sources\CrmBusinessRagSource::class, \App\BusinessModules\Features\AIAssistant\Services\Rag\Sources\CommercialProposalBusinessRagSource::class, \App\BusinessModules\Features\AIAssistant\Services\Rag\Sources\PresaleBusinessRagSource::class, \App\BusinessModules\Features\AIAssistant\Services\Rag\Sources\MarketplaceBusinessRagSource::class, \App\BusinessModules\Features\AIAssistant\Services\Rag\Sources\SalesSupplierRagSource::class];
    }

    public static function observerDefinitions(): array
    {
        $result = [];
        foreach (self::recordDefinitions() as $type => $record) { $result[$record['model']] = [$record['source'], $type]; }
        return $result;
    }

    public static function identifierKinds(): array
    {
        return ['procurement_award_evidence_event' => 'uuid'];
    }

    public static function numericFields(): array
    {
        return array_values(array_unique([...array_merge(...array_column(self::recordDefinitions(), 'numeric_fields')), 'delivery_amount', 'comparison_total']));
    }

    public static function structuredFields(): array
    {
        return array_values(array_unique([...array_merge(...array_column(self::recordDefinitions(), 'fields')), ...array_merge(...array_column(self::parentProjectionDefinitions()['procurement_award_evidence_event'], 'fields'))]));
    }

    public static function safeSelectColumns(): array
    {
        return array_map(static fn (array $record): array => $record['fields'], self::recordDefinitions());
    }

    public static function versionColumns(): array
    {
        return array_map(static fn (array $record): array => $record['version_columns'], self::recordDefinitions());
    }

    public static function factFieldGroups(): array
    {
        $fields = self::structuredFields();
        return ['money' => array_values(array_filter($fields, static fn (string $field): bool => preg_match('/(?:amount$|price$|budget$|^budget_(?:min|max)$|^unit_cost$|_minor$)/', $field) === 1)), 'quantity' => array_values(array_filter($fields, static fn (string $field): bool => str_contains($field, 'quantity'))), 'date' => array_values(array_filter($fields, static fn (string $field): bool => preg_match('/(?:_at|_date|_from|_to|^planned_month)$/', $field) === 1)), 'status' => ['status', 'quality_status', 'reconciliation_status', 'stage', 'outcome_code', 'integrity_status', 'availability_status', 'verification_level'], 'owner' => ['created_by_user_id', 'updated_by_user_id', 'uploaded_by_user_id', 'requested_by_user_id', 'decided_by_user_id', 'actor_user_id', 'actor_id', 'buyer_id']];
    }

    public static function domainDefinitions(): array
    {
        $result = [];
        foreach (self::domainGates() as $domain => [$module]) {
            $types = array_keys(array_filter(self::recordDefinitions(), static fn (array $record): bool => $record['domain'] === $domain));
            $fields = array_values(array_unique(array_merge(...array_map(static fn (string $type): array => self::recordDefinitions()[$type]['fields'], $types))));
            $typeSchema = ['type' => 'string', 'enum' => $types];
            $id = ['type' => ['integer', 'string'], 'minimum' => 1, 'minLength' => 1, 'maxLength' => 36, 'pattern' => '^(?:[1-9][0-9]*|[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|[0-9A-HJKMNP-TV-Z]{26})$'];
            $fieldSchema = ['type' => ['array', 'null'], 'items' => ['type' => 'string', 'enum' => $fields]];
            $schema = static fn (array $properties): array => ['type' => 'object', 'properties' => $properties, 'required' => array_keys($properties), 'additionalProperties' => false];
            $schemas = ['read' => $schema(['entity_type' => $typeSchema, 'id' => $id, 'fields' => $fieldSchema]), 'search' => $schema(['entity_type' => $typeSchema, 'query' => ['type' => 'string', 'maxLength' => 200], 'project_id' => ['type' => ['integer', 'null'], 'minimum' => 1], 'limit' => ['type' => 'integer', 'minimum' => 1, 'maximum' => 20], 'fields' => $fieldSchema]), 'navigation' => $schema(['entity_type' => $typeSchema, 'id' => $id])];
            $fieldPermissions = [];
            foreach (array_intersect($fields, [...self::factFieldGroups()['money'], 'vat_rate', 'premium_ratio', 'median_variance_ratio', 'non_lowest_delta_percent']) as $field) { $fieldPermissions[$field] = match ($domain) { 'commercial_proposals_business' => ['commercial_proposals.amounts.view'], 'presale_estimates' => ['presale_estimates.amounts.view'], default => ['finance.view'] }; }
            $result[] = new AssistantDomainDefinition($domain, $module, $types[0], [], $fields, $schemas, array_keys($schemas), match ($domain) { 'procurement_business' => '/procurement', 'crm_business' => '/crm', 'contractor_marketplace' => '/dashboard/contractor-marketplace', 'sales_supplier_catalog' => '/suppliers', default => '/commercial-proposals' }, $domain, $types, $fieldPermissions, array_intersect_key(self::entityPermissions(), array_flip($types)));
        }
        return $result;
    }

    public static function parentProjectionDefinitions(): array
    {
        return ['procurement_award_evidence_event' => [
            'award_candidates' => ['table' => 'procurement_award_evidence_candidates', 'parent_column' => 'event_id', 'ordinal_column' => 'ordinal', 'fields' => ['event_id', 'ordinal', 'organization_id', 'project_id', 'purchase_request_id', 'supplier_request_id', 'supplier_request_version_id', 'proposal_id', 'proposal_version_id', 'supplier_party_id', 'proposal_status', 'proposal_valid_until', 'subtotal_amount', 'delivery_amount', 'vat_amount', 'total_amount', 'comparison_total', 'currency', 'vat_mode', 'vat_rate', 'delivery_due_date', 'lead_time_days', 'comparable'], 'field_permissions' => array_fill_keys(['subtotal_amount', 'delivery_amount', 'vat_amount', 'total_amount', 'comparison_total', 'vat_rate'], ['finance.view']), 'parents' => ['proposal_id' => ['type' => 'supplier_proposal', 'nullable' => false, 'matches' => ['supplier_request_id' => 'supplier_request_id', 'supplier_request_version_id' => 'supplier_request_version_id']], 'proposal_version_id' => ['type' => 'supplier_proposal_version', 'nullable' => true, 'matches' => ['supplier_proposal_id' => 'proposal_id']], 'supplier_party_id' => ['type' => 'supplier_party', 'nullable' => false]], 'matches' => ['organization_id' => 'organization_id', 'project_id' => 'project_id', 'purchase_request_id' => 'purchase_request_id', 'supplier_request_id' => 'supplier_request_id', 'supplier_request_version_id' => 'supplier_request_version_id']],
            'award_policy' => ['table' => 'procurement_award_policy_versions', 'parent_column' => 'policy_id', 'parent_key' => 'policy_id', 'ordinal_column' => 'version', 'fields' => ['policy_id', 'version', 'schema_version', 'published_by', 'published_at', 'created_at'], 'field_permissions' => [], 'matches' => ['version' => 'policy_version', 'policy_hash' => 'policy_hash']],
        ]];
    }

    public static function globalFanoutEntities(): array
    {
        return array_fill_keys(['marketplace_contractor_profile', 'marketplace_contractor_category', 'marketplace_contractor_document', 'marketplace_contractor_portfolio_item', 'marketplace_contractor_rating', 'marketplace_contractor_region', 'marketplace_work_category', 'crm_pipeline', 'crm_pipeline_stage', 'crm_source'], true);
    }

    public static function rowPredicates(): array
    {
        return ['crm_pipeline' => ['is_active' => true], 'crm_source' => ['is_active' => true], 'marketplace_work_category' => ['is_active' => true]];
    }

    public static function applyActorScope(string $type, Builder $query, User $actor, int $organizationId, AuthorizationService $authorization, AssistantDataAccessPolicy $policy): void
    {
        $table = $query->getModel()->getTable();
        if ($type === 'crm_timeline_event' || $type === 'crm_merge_event') {
            $types = $type === 'crm_merge_event' ? ['companies' => 'crm_company', 'contacts' => 'crm_contact'] : ['companies' => 'crm_company', 'contacts' => 'crm_contact', 'leads' => 'crm_lead', 'deals' => 'crm_deal', 'activities' => 'crm_activity'];
            $column = $type === 'crm_merge_event' ? 'master_id' : 'entity_id';
            $query->where(static function (Builder $scope) use ($types, $column, $actor, $organizationId, $policy, $table): void {
                $scope->whereRaw('1 = 0');
                foreach ($types as $nativeType => $parentType) {
                    $parents = $policy->entityQuery($actor, $organizationId, $parentType);
                    if ($parents === null) { continue; }
                    $parentTable = $parents->getModel()->getTable();
                    $scope->orWhere(static fn (Builder $branch): Builder => $branch->where($table.'.entity_type', $nativeType)->whereIn($table.'.'.$column, $parents->select($parentTable.'.id')));
                }
            });
        } elseif ($type === 'crm_contact_identity' || $type === 'crm_contact_point') {
            $query->where(static fn (Builder $scope): Builder => $scope->whereNotNull($table.'.company_id')->orWhereNotNull($table.'.contact_id'));
        }
    }

    public static function applyOrganizationScope(string $type, Builder $query, User $actor, int $organizationId, AuthorizationService $authorization, AssistantDataAccessPolicy $policy): bool
    {
        if ($organizationId < 1 || ! isset(self::customOrganizationScopes()[$type])) { return false; }
        if ($type === 'marketplace_contractor_profile') {
            SalesBusinessRagSource::applyMarketplaceNetwork($query, $organizationId);
            return true;
        }
        if ($type === 'marketplace_hiring_offer') {
            $table = $query->getModel()->getTable();
            $query->where(static fn (Builder $scope): Builder => $scope->where($table.'.hiring_organization_id', $organizationId)->orWhere($table.'.contractor_organization_id', $organizationId));
            return true;
        }
        return false;
    }

    public static function availabilityDefinitions(): array
    {
        return array_fill_keys(array_keys(array_filter(self::recordDefinitions(), static fn (array $record): bool => $record['domain'] === 'presale_estimates')), ['availability' => 'unavailable', 'reason_code' => 'no_current_canonical_read_entitlement', 'reason' => 'Внутренний процесс не имеет подключённого модуля чтения']);
    }

    public static function retrievalCoverageDefinitions(): array
    {
        return array_map(static fn (array $record): array => $record['domain'] === 'presale_estimates'
            ? ['indexed' => false, 'mode' => 'unavailable', 'availability' => 'unavailable', 'reason_code' => 'no_current_canonical_read_entitlement', 'reason' => 'Внутренний процесс не имеет подключённого модуля чтения']
            : ['indexed' => true, 'mode' => 'indexed_private', 'reason' => 'Explicit finite scalar fields; current organization, project and parent ACL are applied before retrieval limits.'], self::recordDefinitions());
    }

    public static function entityLabels(): array { return (require dirname(__DIR__, 6).'/lang/ru/ai_assistant_sales.php')['entities']; }
    public static function fieldLabels(): array { return (require dirname(__DIR__, 6).'/lang/ru/ai_assistant_sales.php')['fields']; }
}
