openapi: 3.1.0
info:
  title: "ProHelper Mobile API"
  description: |
    Спецификация API мобильного приложения. Используйте для описания эндпоинтов `/api/v1/mobile`.
  version: "1.0.0"
servers:
  - url: "/api/v1/mobile"
    description: "Production server"
  - url: "http://localhost:8000/api/v1/mobile"
    description: "Local development"
paths:
  $ref: './paths/index.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas: {}
  responses: {}
  parameters: {} 