<?php

declare(strict_types=1);

return [
    'quote_version' => 1,
    'currency' => 'RUB',
    'free' => [
        'users' => 3,
        'projects' => 2,
        'storage_gb' => 2,
        'contractors' => 10,
        'holding_organizations' => 1,
        'ai_requests_month' => 50,
        'ai_estimates_month' => 0,
        'document_pages_month' => 0,
        'exports_month' => 0,
        'commercial_proposals_month' => 0,
    ],
    'limits' => [
        'users' => ['name_key' => 'billing.quota.limit_names.users', 'unit' => 'user', 'enforcement' => 'hard'],
        'projects' => ['name_key' => 'billing.quota.limit_names.projects', 'unit' => 'project', 'enforcement' => 'hard'],
        'storage_gb' => ['name_key' => 'billing.quota.limit_names.storage_gb', 'unit' => 'gb', 'enforcement' => 'hard'],
        'contractors' => ['name_key' => 'billing.quota.limit_names.contractors', 'unit' => 'contractor', 'enforcement' => 'soft'],
        'holding_organizations' => ['name_key' => 'billing.quota.limit_names.holding_organizations', 'unit' => 'organization', 'enforcement' => 'soft'],
        'ai_requests_month' => ['name_key' => 'billing.quota.limit_names.ai_requests_month', 'unit' => 'request', 'enforcement' => 'hard'],
        'ai_estimates_month' => ['name_key' => 'billing.quota.limit_names.ai_estimates_month', 'unit' => 'estimate', 'enforcement' => 'hard'],
        'document_pages_month' => ['name_key' => 'billing.quota.limit_names.document_pages_month', 'unit' => 'page', 'enforcement' => 'hard'],
        'exports_month' => ['name_key' => 'billing.quota.limit_names.exports_month', 'unit' => 'export', 'enforcement' => 'soft'],
        'commercial_proposals_month' => ['name_key' => 'billing.quota.limit_names.commercial_proposals_month', 'unit' => 'proposal', 'enforcement' => 'soft'],
    ],
    'resources' => [
        'extra_users' => [
            'limit_key' => 'users',
            'name_key' => 'billing.quota.resource_names.extra_users',
            'unit' => 'user',
            'step' => 1,
            'min' => 0,
            'max_self_service' => 200,
            'pricing_model' => 'linear',
            'price_minor' => 30000,
            'requires_package' => null,
            'sort_order' => 10,
        ],
        'extra_projects' => [
            'limit_key' => 'projects',
            'name_key' => 'billing.quota.resource_names.extra_projects',
            'unit' => 'project',
            'step' => 1,
            'min' => 0,
            'max_self_service' => 100,
            'pricing_model' => 'linear',
            'price_minor' => 50000,
            'requires_package' => null,
            'sort_order' => 20,
        ],
        'storage_gb' => [
            'limit_key' => 'storage_gb',
            'name_key' => 'billing.quota.resource_names.storage_gb',
            'unit' => 'gb',
            'step' => 10,
            'min' => 0,
            'max_self_service' => 1000,
            'pricing_model' => 'linear',
            'price_minor' => 2000,
            'requires_package' => null,
            'sort_order' => 30,
        ],
        'extra_holding_organizations' => [
            'limit_key' => 'holding_organizations',
            'name_key' => 'billing.quota.resource_names.extra_holding_organizations',
            'unit' => 'organization',
            'step' => 1,
            'min' => 0,
            'max_self_service' => 50,
            'pricing_model' => 'linear',
            'price_minor' => 100000,
            'requires_package' => null,
            'requires_module' => 'multi-organization',
            'sort_order' => 35,
        ],
        'extra_contractors' => [
            'limit_key' => 'contractors',
            'name_key' => 'billing.quota.resource_names.extra_contractors',
            'unit' => 'contractor',
            'step' => 10,
            'min' => 0,
            'max_self_service' => 500,
            'pricing_model' => 'linear',
            'price_minor' => 10000,
            'requires_package' => 'sales-contractors',
            'sort_order' => 40,
        ],
        'extra_ai_requests' => [
            'limit_key' => 'ai_requests_month',
            'name_key' => 'billing.quota.resource_names.extra_ai_requests',
            'unit' => 'request',
            'step' => 100,
            'min' => 0,
            'max_self_service' => 10000,
            'pricing_model' => 'linear',
            'price_minor' => 500,
            'requires_package' => null,
            'requires_module' => 'ai-assistant',
            'sort_order' => 50,
        ],
        'extra_ai_estimates' => [
            'limit_key' => 'ai_estimates_month',
            'name_key' => 'billing.quota.resource_names.extra_ai_estimates',
            'unit' => 'estimate',
            'step' => 10,
            'min' => 0,
            'max_self_service' => 1000,
            'pricing_model' => 'linear',
            'price_minor' => 5000,
            'requires_package' => 'estimates-norms',
            'requires_module' => 'ai-estimates',
            'sort_order' => 60,
        ],
        'extra_document_pages' => [
            'limit_key' => 'document_pages_month',
            'name_key' => 'billing.quota.resource_names.extra_document_pages',
            'unit' => 'page',
            'step' => 100,
            'min' => 0,
            'max_self_service' => 5000,
            'pricing_model' => 'linear',
            'price_minor' => 1000,
            'requires_package' => 'estimates-norms',
            'sort_order' => 70,
        ],
        'extra_exports' => [
            'limit_key' => 'exports_month',
            'name_key' => 'billing.quota.resource_names.extra_exports',
            'unit' => 'export',
            'step' => 100,
            'min' => 0,
            'max_self_service' => 10000,
            'pricing_model' => 'linear',
            'price_minor' => 200,
            'requires_package' => null,
            'sort_order' => 80,
        ],
        'extra_commercial_proposals' => [
            'limit_key' => 'commercial_proposals_month',
            'name_key' => 'billing.quota.resource_names.extra_commercial_proposals',
            'unit' => 'proposal',
            'step' => 50,
            'min' => 0,
            'max_self_service' => 5000,
            'pricing_model' => 'linear',
            'price_minor' => 500,
            'requires_package' => 'sales-contractors',
            'sort_order' => 90,
        ],
    ],
];
