<?php

declare(strict_types=1);

return [
    'url' => rtrim((string) env('GLITCHTIP_URL', ''), '/'),
    'token' => env('GLITCHTIP_TOKEN'),
    'organization' => env('GLITCHTIP_ORG'),
    'project' => env('GLITCHTIP_PROJECT'),
    'period' => env('GLITCHTIP_PERIOD', '24h'),
    'internal_token' => env('GLITCHTIP_INTERNAL_TOKEN'),
    'webhook_secret' => env('GLITCHTIP_WEBHOOK_SECRET'),
    'allow_unsigned_webhooks' => (bool) env('GLITCHTIP_ALLOW_UNSIGNED_WEBHOOKS', false),
    'latest_incident_cache_key' => env('GLITCHTIP_LATEST_INCIDENT_CACHE_KEY', 'glitchtip.latest_incident'),
    'latest_incident_ttl_seconds' => (int) env('GLITCHTIP_LATEST_INCIDENT_TTL_SECONDS', 86400),
    'issues_limit' => (int) env('GLITCHTIP_ISSUES_LIMIT', 20),
    'issue_sync_cache_prefix' => env('GLITCHTIP_ISSUE_SYNC_CACHE_PREFIX', 'glitchtip.issue_sync'),
    'auto_create_github_issue' => (bool) env('GLITCHTIP_AUTO_CREATE_GITHUB_ISSUE', false),
    'reporting' => [
        'enabled' => (bool) env('GLITCHTIP_REPORTING_ENABLED', true),
        'capture_unexpected' => (bool) env('GLITCHTIP_CAPTURE_UNEXPECTED_ERRORS', true),
        'default_level' => env('GLITCHTIP_DEFAULT_LEVEL', 'error'),
        'manual_capture_levels' => array_values(array_filter(array_map('trim', explode(',', (string) env('GLITCHTIP_MANUAL_CAPTURE_LEVELS', 'warning'))))),
        'stop_ignoring' => [
            \Symfony\Component\HttpKernel\Exception\HttpException::class,
            \Illuminate\Http\Exceptions\PostTooLargeException::class,
        ],
        'capture' => [
            'exceptions' => [
                \Illuminate\Database\QueryException::class => 'fatal',
                \PDOException::class => 'fatal',
                \Predis\Connection\ConnectionException::class => 'fatal',
                \Illuminate\Http\Client\ConnectionException::class => 'error',
                \Illuminate\Http\Client\RequestException::class => 'error',
                \League\Flysystem\UnableToWriteFile::class => 'error',
                \League\Flysystem\UnableToReadFile::class => 'error',
                \InvalidArgumentException::class => 'fatal',
                \Illuminate\Http\Exceptions\PostTooLargeException::class => 'warning',
                \App\Exceptions\AI\AIAuthenticationException::class => 'fatal',
                \App\Exceptions\AI\AIParsingException::class => 'error',
                \App\Exceptions\AI\AIServiceUnavailableException::class => 'warning',
            ],
            'http_statuses' => [
                500 => 'error',
                502 => 'error',
                503 => 'error',
                504 => 'error',
            ],
            'http_status_min' => 500,
            'http_status_min_level' => 'error',
        ],
        'ignore' => [
            'exceptions' => [
                \Illuminate\Validation\ValidationException::class,
                \Illuminate\Auth\AuthenticationException::class,
                \Illuminate\Auth\Access\AuthorizationException::class,
                \Symfony\Component\HttpKernel\Exception\NotFoundHttpException::class,
                \Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException::class,
                \Symfony\Component\HttpKernel\Exception\TooManyRequestsHttpException::class,
                \Illuminate\Database\Eloquent\ModelNotFoundException::class,
                \App\Exceptions\Billing\InsufficientBalanceException::class,
                \App\Exceptions\AI\AIQuotaExceededException::class,
            ],
            'http_statuses' => [
                400,
                401,
                403,
                404,
                405,
                419,
                422,
                429,
            ],
        ],
        'business_logic' => [
            'capture' => (bool) env('GLITCHTIP_CAPTURE_BUSINESS_LOGIC_ERRORS', false),
            'level' => env('GLITCHTIP_BUSINESS_LOGIC_LEVEL', 'warning'),
        ],
    ],
    'github' => [
        'token' => env('GITHUB_ISSUES_TOKEN'),
        'repository' => env('GITHUB_ISSUES_REPOSITORY'),
        'base_branch' => env('GITHUB_PULL_REQUEST_BASE', 'main'),
        'labels' => array_values(array_filter(array_map('trim', explode(',', (string) env('GITHUB_ISSUES_LABELS', 'bug,glitchtip'))))),
    ],
];
