<?php

use Illuminate\Support\Str;

$estimateGenerationUnitsMinProcesses = max(1, (int) env('ESTIMATE_GENERATION_UNITS_MIN_PROCESSES', 1));
$estimateGenerationUnitsMaxProcesses = max(
    $estimateGenerationUnitsMinProcesses,
    (int) env('ESTIMATE_GENERATION_UNITS_MAX_PROCESSES', 3),
);

return [
    'domain' => env('HORIZON_DOMAIN'),
    'path' => env('HORIZON_PATH', 'horizon'),
    'use' => 'default',
    'prefix' => env('HORIZON_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_horizon:'),

    'middleware' => ['web'],

    'waits' => [
        'redis_estimate_generation:estimate-generation' => 120,
        'redis_estimate_generation:estimate-generation-units' => 120,
        'redis_estimate_generation:estimate-generation-unit-maintenance' => 60,
        'redis_estimate_generation_benchmarks:estimate-generation-benchmarks' => 300,
        'redis:estimate-generation' => 120,
        'redis:notifications-critical' => 30,
        'redis:notifications-high' => 60,
        'redis:notifications' => 120,
        'redis:notifications-low' => 300,
        'redis:ai-rag' => 600,
        'redis_ai_rag:ai-rag' => 600,
        'redis:'.env('EPM_DATA_MART_QUEUE', 'epm-data-mart') => 600,
    ],

    'trim' => [
        'recent' => 60,
        'pending' => 60,
        'completed' => 60,
        'recent_failed' => 10080,
        'failed' => 10080,
        'monitored' => 10080,
    ],

    'silenced' => [
    ],

    'fast_termination' => false,

    'memory_limit' => (int) env('HORIZON_MEMORY_LIMIT', 256),

    'defaults' => [
        'supervisor-1' => [
            'connection' => 'redis',
            'queue' => ['default'],
            'balance' => 'auto',
            'autoScalingStrategy' => 'time',
            'maxProcesses' => 1,
            'maxTime' => 0,
            'maxJobs' => 0,
            'memory' => 128,
            'tries' => 1,
            'timeout' => 60,
            'nice' => 0,
        ],
    ],

    'environments' => [
        'production' => [
            'supervisor-critical' => [
                'connection' => 'redis',
                'queue' => ['notifications-critical'],
                'balance' => 'auto',
                'autoScalingStrategy' => 'time',
                'minProcesses' => 2,
                'maxProcesses' => 10,
                'balanceMaxShift' => 1,
                'balanceCooldown' => 3,
                'tries' => 5,
                'timeout' => 120,
            ],
            'supervisor-high' => [
                'connection' => 'redis',
                'queue' => ['notifications-high'],
                'balance' => 'auto',
                'autoScalingStrategy' => 'time',
                'minProcesses' => 1,
                'maxProcesses' => 5,
                'tries' => 3,
                'timeout' => 120,
            ],
            'supervisor-normal' => [
                'connection' => 'redis',
                'queue' => ['notifications', 'default'],
                'balance' => 'auto',
                'autoScalingStrategy' => 'time',
                'minProcesses' => 1,
                'maxProcesses' => 3,
                'tries' => 3,
                'timeout' => 300,
            ],
            'supervisor-low' => [
                'connection' => 'redis',
                'queue' => ['notifications-low'],
                'balance' => 'simple',
                'processes' => 1,
                'tries' => 2,
                'timeout' => 600,
            ],
            'supervisor-imports' => [
                'connection' => 'redis',
                'queue' => ['imports'],
                'balance' => 'auto',
                'autoScalingStrategy' => 'time',
                'minProcesses' => 1,
                'maxProcesses' => 5,
                'tries' => 1,
                'timeout' => 1200,
            ],
            'supervisor-estimate-generation' => [
                'connection' => 'redis_estimate_generation',
                'queue' => ['estimate-generation'],
                'balance' => 'auto',
                'autoScalingStrategy' => 'time',
                'minProcesses' => 1,
                'maxProcesses' => 2,
                'tries' => 3,
                'timeout' => 1800,
                'memory' => 512,
            ],
            'supervisor-estimate-generation-units' => [
                'connection' => 'redis_estimate_generation',
                'queue' => ['estimate-generation-units'],
                'balance' => 'auto',
                'autoScalingStrategy' => 'time',
                'minProcesses' => $estimateGenerationUnitsMinProcesses,
                'maxProcesses' => $estimateGenerationUnitsMaxProcesses,
                'balanceMaxShift' => 1,
                'balanceCooldown' => 3,
                'tries' => 20,
                'timeout' => 2100,
                'memory' => 512,
            ],
            'supervisor-estimate-generation-unit-maintenance' => [
                'connection' => 'redis_estimate_generation',
                'queue' => ['estimate-generation-unit-maintenance'],
                'balance' => 'simple',
                'processes' => 1,
                'tries' => 3,
                'timeout' => 300,
                'memory' => 256,
            ],
            'supervisor-estimate-generation-benchmarks' => [
                'connection' => 'redis_estimate_generation_benchmarks',
                'queue' => ['estimate-generation-benchmarks'],
                'balance' => 'simple',
                'processes' => 1,
                'tries' => 2,
                'timeout' => 3700,
                'memory' => 512,
                'nice' => 10,
            ],
            'supervisor-ai-rag' => [
                'connection' => env('AI_RAG_QUEUE_CONNECTION', 'redis_ai_rag'),
                'queue' => [env('AI_RAG_QUEUE', 'ai-rag')],
                'balance' => 'auto',
                'autoScalingStrategy' => 'time',
                'minProcesses' => 1,
                'maxProcesses' => (int) env('AI_RAG_HORIZON_MAX_PROCESSES', 2),
                'tries' => 3,
                'timeout' => max(7200, (int) env('AI_RAG_JOB_TIMEOUT', 7200)),
                'memory' => 512,
                'nice' => 5,
            ],
            'supervisor-epm-data-mart' => [
                'connection' => 'redis',
                'queue' => [env('EPM_DATA_MART_QUEUE', 'epm-data-mart')],
                'balance' => 'auto',
                'autoScalingStrategy' => 'time',
                'minProcesses' => 1,
                'maxProcesses' => 2,
                'tries' => 3,
                'timeout' => 1800,
                'memory' => 512,
                'nice' => 5,
            ],
        ],

        'local' => [
            'supervisor-estimate-generation-units' => [
                'connection' => 'redis_estimate_generation',
                'queue' => ['estimate-generation-units'],
                'balance' => 'simple',
                'processes' => max(1, (int) env('ESTIMATE_GENERATION_UNITS_LOCAL_PROCESSES', 1)),
                'tries' => 20,
                'timeout' => 2100,
                'memory' => 512,
            ],
            'supervisor-estimate-generation-unit-maintenance' => [
                'connection' => 'redis_estimate_generation',
                'queue' => ['estimate-generation-unit-maintenance'],
                'balance' => 'simple',
                'processes' => 1,
                'tries' => 3,
                'timeout' => 300,
                'memory' => 256,
            ],
            'supervisor-estimate-generation-benchmarks' => [
                'connection' => 'redis_estimate_generation_benchmarks',
                'queue' => ['estimate-generation-benchmarks'],
                'balance' => 'simple',
                'processes' => 1,
                'tries' => 2,
                'timeout' => 3700,
                'memory' => 512,
                'nice' => 10,
            ],
            'supervisor-estimate-generation' => [
                'connection' => 'redis_estimate_generation',
                'queue' => ['estimate-generation'],
                'balance' => 'simple',
                'processes' => 1,
                'tries' => 3,
                'timeout' => 1800,
                'memory' => 512,
            ],
            'supervisor-ai-rag' => [
                'connection' => env('AI_RAG_QUEUE_CONNECTION', 'redis_ai_rag'),
                'queue' => [env('AI_RAG_QUEUE', 'ai-rag')],
                'balance' => 'simple',
                'processes' => 1,
                'tries' => 3,
                'timeout' => max(7200, (int) env('AI_RAG_JOB_TIMEOUT', 7200)),
                'memory' => 512,
            ],
            'supervisor-epm-data-mart' => [
                'connection' => 'redis',
                'queue' => [env('EPM_DATA_MART_QUEUE', 'epm-data-mart')],
                'balance' => 'simple',
                'processes' => 1,
                'tries' => 3,
                'timeout' => 1800,
                'memory' => 512,
            ],
            'supervisor-1' => [
                'connection' => 'redis',
                'queue' => ['imports', 'notifications-critical', 'notifications-high', 'notifications', 'notifications-low', 'default'],
                'balance' => 'simple',
                'processes' => 3,
                'tries' => 3,
                'timeout' => 60,
            ],
        ],
    ],
];
