<?php

declare(strict_types=1);

return [
    'foundation_modules' => [
        'organizations',
        'users',
        'project-management',
        'contract-management',
        'catalog-management',
        'workflow-management',
        'act-reporting',
        'payments',
        'reports',
        'dashboard-widgets',
        'data-filters',
        'brigades',
    ],

    'module_classifications' => [
        'organizations' => 'foundation',
        'users' => 'foundation',
        'project-management' => 'foundation',
        'contract-management' => 'foundation',
        'catalog-management' => 'foundation',
        'workflow-management' => 'foundation',
        'act-reporting' => 'foundation',
        'payments' => 'foundation',
        'reports' => 'foundation',
        'dashboard-widgets' => 'foundation',
        'data-filters' => 'foundation',
        'brigades' => 'foundation',
        'schedule-management' => 'package',
        'site-requests' => 'package',
        'time-tracking' => 'package',
        'basic-warehouse' => 'package',
        'procurement' => 'package',
        'budget-estimates' => 'package',
        'budgeting' => 'package',
        'crm' => 'package',
        'design-management' => 'package',
        'quality-control' => 'package',
        'executive-documentation' => 'package',
        'safety-management' => 'package',
        'machinery-operations' => 'package',
        'workforce-management' => 'package',
        'production-labor' => 'package',
        'change-management' => 'package',
        'handover-acceptance' => 'package',
        'multi-organization' => 'package',
        'material-analytics' => 'addon',
        'data-export' => 'integration',
        'advance-accounting' => 'addon',
        'file-management' => 'addon',
        'rate-management' => 'addon',
        'report-templates' => 'addon',
        'ai-assistant' => 'addon',
        'ai-estimates' => 'addon',
        'integrations' => 'integration',
        'one-c-basic-exchange' => 'addon',
        'video-monitoring' => 'addon',
        'contractor-portal' => 'addon',
        'system-logs' => 'internal',
    ],

    'module_aliases' => [
        'production-labor' => 'workforce-management',
    ],

    'package_children' => [
        'workforce-management' => [
            'production-labor',
        ],
    ],
];
