openapi: 3.1.0
info:
  title: "ProHelper LK API"
  description: |
    Спецификация API личного кабинета (Landing). Добавляйте детали по мере готовности.
  version: "1.0.0"
servers:
  - url: "/api/v1/landing"
    description: "Production server"
  - url: "http://localhost:8000/api/v1/landing"
    description: "Local development"
paths:
  $ref: './paths/index.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    # Авторизация (обновлено)
    LkLoginRequest:
      $ref: './components/schemas/LkLoginRequest.yaml'
    LkLoginResponse:
      $ref: './components/schemas/LkLoginResponse.yaml'
    LkUpdateProfileRequest:
      $ref: './components/schemas/LkUpdateProfileRequest.yaml'
    LkUserProfile:
      $ref: './components/schemas/LkUserProfile.yaml'
    
    # Организация (обновлено)
    LkUpdateOrganizationRequest:
      $ref: './components/schemas/LkUpdateOrganizationRequest.yaml'
    LkOrganizationProfile:
      $ref: './components/schemas/LkOrganizationProfile.yaml'
    LkOrganizationVerification:
      $ref: './components/schemas/LkOrganizationVerification.yaml'
    
    # DaData API
    DaDataSuggestRequest:
      $ref: './components/schemas/DaDataSuggestRequest.yaml'
    DaDataSuggestResponse:
      $ref: './components/schemas/DaDataSuggestResponse.yaml'
  responses: {}
  parameters: {}
