openapi: 3.1.0
info:
  title: "ProHelper LK API"
  description: |
    Спецификация API личного кабинета (Landing). Добавляйте детали по мере готовности.
  version: "1.0.0"
servers:
  - url: "/api/v1/landing"
    description: "Production server"
  - url: "http://localhost:8000/api/v1/landing"
    description: "Local development"
paths: {}
components:
  schemas: {}
  parameters: {}
  responses: {}
  securitySchemes: {} 