openapi: 3.1.0
info:
  title: "ProHelper Landing Admin API"
  description: |
    Спецификация API админ-панели (Landing Admin). Добавляйте пути через `$ref` в папку `paths/`.
  version: "1.0.0"
servers:
  - url: "/api/v1/landing"
    description: "Production server"
  - url: "http://localhost:8000/api/v1/landing"
    description: "Local development"
paths:
  $ref: './paths/index.yaml'
components:
  securitySchemes:
    $ref: './components/securitySchemes.yaml'
  schemas:
    LandingAdmin:
      $ref: './components/schemas/LandingAdmin.yaml'
    LandingAdminCreateRequest:
      $ref: './components/schemas/LandingAdminCreateRequest.yaml'
    LandingAdminUpdateRequest:
      $ref: './components/schemas/LandingAdminUpdateRequest.yaml'
    LoginRequest:
      $ref: './components/schemas/LoginRequest.yaml'
    TokenResponse:
      $ref: './components/schemas/TokenResponse.yaml'
    
    # Blog Schemas
    BlogArticle:
      $ref: './components/schemas/BlogArticle.yaml'
    BlogArticleCreateRequest:
      $ref: './components/schemas/BlogArticleCreateRequest.yaml'
    BlogArticleUpdateRequest:
      $ref: './components/schemas/BlogArticleUpdateRequest.yaml'
    BlogCategory:
      $ref: './components/schemas/BlogCategory.yaml'
    BlogCategoryRequest:
      $ref: './components/schemas/BlogCategoryRequest.yaml'
    BlogComment:
      $ref: './components/schemas/BlogComment.yaml'
    BlogCommentStatusRequest:
      $ref: './components/schemas/BlogCommentStatusRequest.yaml'
    BlogTag:
      $ref: './components/schemas/BlogTag.yaml'
    BlogSeoSettings:
      $ref: './components/schemas/BlogSeoSettings.yaml'
    BlogDashboard:
      $ref: './components/schemas/BlogDashboard.yaml'
    BlogAnalytics:
      $ref: './components/schemas/BlogAnalytics.yaml'
    
  responses: {}
  parameters: {} 