name: Monitoring Health Check

concurrency:
  group: monitoring-health
  cancel-in-progress: true

on:
  schedule:
    # Проверка каждые 15 минут
    - cron: '*/15 * * * *'
  workflow_dispatch:
    # Ручной запуск

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Monitoring Services (appleboy)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 89.111.153.146
          username: root
          key: ${{ secrets.DEPLOY }}
          script: |
            cd /var/www/prohelper
            if ! docker ps | grep -q prometheus; then
              echo 'Prometheus не запущен, перезапускаем мониторинг...'
              ./start-monitoring.sh
            fi
            services_down=0
            if ! curl -sf http://localhost:9090/-/healthy >/dev/null; then
              echo 'Prometheus недоступен'
              services_down=1
            fi
            if ! curl -sf http://localhost:3000/api/health >/dev/null; then
              echo 'Grafana недоступна'
              services_down=1
            fi
            if ! curl -sf http://localhost:3100/ready >/dev/null; then
              echo 'Loki недоступен'
              services_down=1
            fi
            if [ $services_down -eq 1 ]; then
              echo 'Обнаружены проблемы с мониторингом, перезапускаем точечно...'
              (command -v docker-compose >/dev/null && docker-compose restart prometheus grafana loki || docker compose restart prometheus grafana loki)
              sleep 60
              if ! curl -sf http://localhost:9090/-/healthy >/dev/null; then
                echo 'Критическая ошибка: Prometheus не восстановился'
                exit 1
              fi
            else
              echo 'Все сервисы мониторинга работают нормально'
            fi

      - name: Check Disk Space (appleboy)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 89.111.153.146
          username: root
          key: ${{ secrets.DEPLOY }}
          script: |
            disk_usage=$(df / | tail -1 | awk '{print $5}' | sed 's/%//')
            if [ $disk_usage -gt 85 ]; then
              echo "Предупреждение: Диск заполнен на ${disk_usage}%"
              docker system prune -f --volumes
              find /var/www/prohelper/storage/logs -name '*.log' -mtime +7 -delete
            fi

      - name: Backup Monitoring Config (appleboy)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 89.111.153.146
          username: root
          key: ${{ secrets.DEPLOY }}
          script: |
            cd /var/www/prohelper
            tar -czf /tmp/monitoring-backup-$(date +%Y%m%d).tar.gz monitoring/ docker-compose.yml start-monitoring.sh stop-monitoring.sh
            find /tmp -name 'monitoring-backup-*.tar.gz' -mtime +7 -delete

      - name: Send Status Notification
        if: failure()
        run: |
          echo "Обнаружены критические проблемы с мониторингом на сервере"
          # Здесь можно добавить отправку уведомлений в Slack/Telegram
          # curl -X POST -H 'Content-type: application/json' \
          #   --data '{"text":"🚨 Критические проблемы с мониторингом на проде!"}' \
          #   ${{ secrets.SLACK_WEBHOOK_URL }}